import { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { isAutomated, isHandEntered, sourceLabel } from "../../performanceStandardsVocabulary.js";
import type { AssessmentCap, AssessmentDispute, AssessmentEvidence, AssessmentPeriod, AssessmentPeriodStatus, ComplianceOccurrence, ContractorPerformanceStandard, ContractorRecord, ContractorStandardTier, ManualMetricEntry, PeriodKpiAssessment } from "@mvta/shared";
import { api } from "../../../config.js";
import { useAuth } from "../../../auth/AuthContext.js";
import { ReportWorkflow } from "./ReportWorkflow.js";
import { Empty, formatDate, formatMonth, money } from "./assessmentFormat.js";
import { usePeriodRows } from "./usePeriodRows.js";
import { reviewDisplay } from "./reviewDisplay.js";
import { useAppDialog } from "../../../components/AppDialog.js";
import "./assessment.css";

type Page = "scorecard"|"detail"|"occurrences"|"metrics"|"review"|"caps"|"report"|"disputes"|"standards";
const NAV: {key:Page;label:string}[] = [
  {key:"scorecard",label:"Scorecard"},{key:"detail",label:"KPI Detail"},{key:"occurrences",label:"Occurrence Log"},
  {key:"metrics",label:"Monthly Metrics"},{key:"review",label:"Manager Review"},{key:"caps",label:"CAPs"},
  {key:"report",label:"Report"},{key:"disputes",label:"Disputes"},{key:"standards",label:"Standards Admin"},
];
const currentMonth=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`};
const inputDate=(value:string|null|undefined)=>{const d=value?.replace(/\D/g,"")??"";return d.length===8?`${d.slice(0,4)}-${d.slice(4,6)}-${d.slice(6,8)}`:""};

export function AssessmentModule(){
  const {roles}=useAuth();
  const [page,setPage]=useState<Page>("scorecard"),[periods,setPeriods]=useState<AssessmentPeriod[]>([]),[contractors,setContractors]=useState<ContractorRecord[]>([]),[standards,setStandards]=useState<ContractorPerformanceStandard[]>([]),[tiers,setTiers]=useState<ContractorStandardTier[]>([]),[occurrences,setOccurrences]=useState<ComplianceOccurrence[]>([]),[metrics,setMetrics]=useState<ManualMetricEntry[]>([]),[selected,setSelected]=useState(""),[month,setMonth]=useState(currentMonth()),[showContractors,setShowContractors]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[tableReady,setTableReady]=useState(true);
  const load=useCallback(async()=>{try{setError("");const [p,c,s,o,m]=await Promise.all([api.getAssessmentPeriods(),api.getContractors(),api.getPerformanceStandards(),api.getComplianceOccurrences(),api.getManualMetrics()]);setPeriods(p.periods);setContractors(c.contractors);setStandards(s.standards);setTiers(s.tiers??[]);setOccurrences(o.occurrences);setMetrics(m.metrics);setTableReady(p.diagnostics.table_ready&&c.diagnostics.table_ready&&s.diagnostics.table_ready);setSelected(v=>v||p.periods[0]?.id||"");}catch(e){setError(e instanceof Error?e.message:"Unable to load assessment workspace")}},[]);
  useEffect(()=>{void load()},[load]);
  const [refreshKey,setRefreshKey]=useState(0);
  const {rows,detailId,setDetailId,error:rowsError}=usePeriodRows(api.getPeriodAssessments,selected,refreshKey);
  const period=periods.find(p=>p.id===selected),activeContractors=contractors.filter(c=>c.is_active),detail=rows.find(r=>r.id===detailId),periodOccurrences=period?occurrences.filter(o=>o.contractor_id===period.contractor_id&&o.service_date.startsWith(period.service_month)):occurrences,periodMetrics=period?metrics.filter(m=>m.contractor_id===period.contractor_id&&m.service_month===period.service_month):metrics;
  const totals=useMemo(()=>({proposed:rows.reduce((s,r)=>s+Number(r.proposed_amount||0),0),final:rows.reduce((s,r)=>s+Number(r.recommended_amount??r.final_amount??0),0),pending:rows.filter(r=>!r.recommended_action).length,caps:rows.filter(r=>r.cap_required||r.tier_label==="tier2").length}),[rows]);
  // Rows are reloaded by the period loader, keyed on refreshKey, so an
  // action's refresh can never land on a period selected after it started.
  async function act(action:()=>Promise<unknown>){setBusy(true);setError("");try{await action();await load();setRefreshKey(k=>k+1)}catch(e){setError(e instanceof Error?e.message:"Action failed")}finally{setBusy(false)}}
  if(!tableReady)return <div className="concept-banner">Performance Assessment database objects are not ready. Apply migration 030, then migration 031.</div>;
  return <div className="assessment-module">
    <div className="assessment-toolbar"><div><span className="assessment-eyebrow">Performance governance</span><h2>Contractor Performance Assessment</h2><p>Monthly performance standards scoring, evidence, review, and issuance.</p></div><button className="assessment-manage" onClick={()=>setShowContractors(v=>!v)}>{showContractors?"Close contractor setup":"Manage contractors"}</button></div>
    {showContractors&&<ContractorSetup contractors={contractors} canEdit={roles.includes("OCC.Admin")} busy={busy} onSave={(id,input)=>void act(()=>api.putContractor(id,input))}/>}
    {!activeContractors.length&&!showContractors&&<div className="assessment-warning"><strong>Setup required:</strong> no active contractor is configured. <button className="assessment-link-button" onClick={()=>setShowContractors(true)}>Set up a contractor</button> to begin.</div>}
    {(error||rowsError)&&<div className="assessment-error">{error||rowsError}</div>}
    <div className="assessment-context-bar"><label><span>Contractor</span><select aria-label="Contractor" id="assessment-contractor" disabled={!activeContractors.length}><option value="">{activeContractors.length?"Choose a contractor":"No active contractors"}</option>{activeContractors.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><span>Service month</span><input type="month" aria-label="Service month" value={month} onChange={e=>setMonth(e.target.value)}/></label><button className="btn-primary" disabled={busy||!activeContractors.length||month.length!==7} onClick={()=>{const el=document.getElementById("assessment-contractor") as HTMLSelectElement;if(el.value)void act(async()=>{const opened=await api.openAssessmentPeriod(el.value,month.replace("-",""));setSelected(opened.id)})}}>Open assessment month</button></div>
    <nav className="assessment-nav" aria-label="Assessment sections">{NAV.map(n=><button key={n.key} className={page===n.key?"active":""} onClick={()=>setPage(n.key)}>{n.label}</button>)}</nav>
    <div className="assessment-period"><label className="assessment-period-field"><span>Assessment period</span><select aria-label="Assessment period" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select an assessment period</option>{periods.map(p=><option key={p.id} value={p.id}>{p.contractor_name} · {formatMonth(p.service_month)} · {p.status}</option>)}</select></label>{period&&<span className={`assessment-status ${period.status}`}>{period.status.replace("_"," ")}</span>}</div>
    {page==="scorecard"&&<><Stats totals={totals}/>{!period?<Empty>Open or select an Assessment Period to view its scorecard.</Empty>:<ScoreTable rows={rows} status={period.status} busy={busy} onDetail={r=>{setDetailId(r.id);setPage("detail")}}/>}</>}
    {page==="detail"&&(!period?<Empty>Select an Assessment Period, then choose a KPI.</Empty>:<><select aria-label="KPI" value={detailId} onChange={e=>setDetailId(e.target.value)}>{rows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select>{detail?<><KpiDetail row={detail} occurrences={periodOccurrences.filter(o=>o.standard_id===detail.standard_id)}/><Evidence assessment={detail}/></>:<Empty>Compute this period to produce KPI detail.</Empty>}</>)}
    {page==="occurrences"&&<Occurrences rows={periodOccurrences} periodSelected={Boolean(period)} busy={busy} onAmount={(o,amount,note)=>void act(()=>api.setOccurrenceAssessedAmount(o.id,amount,note))} onReview={(o,status,attribution,reason)=>void act(()=>api.reviewComplianceOccurrence(o.id,status,attribution,reason))}/>}
    {page==="metrics"&&<Metrics rows={periodMetrics} standards={standards} period={period} busy={busy} onSave={(standard_id,value,note)=>period&&void act(()=>api.putManualMetric({standard_id,contractor_id:period.contractor_id,service_month:period.service_month,metric_value:value,source_note:note}))}/>}
    {page==="review"&&<ManagerReview period={period} rows={rows} totals={totals} busy={busy} onReview={(r,a,amount,reason)=>void act(()=>api.reviewPeriodAssessment(r.id,a,amount,reason))} onCompute={()=>period&&void act(()=>api.computeAssessmentPeriod(period.id))} onFinalize={()=>period&&void act(()=>api.finalizeAssessmentPeriod(period.id))}/>}
    {page==="caps"&&<Caps rows={rows} period={period}/>}
    {page==="report"&&<ReportWorkflow period={period} busy={busy} act={act}/>}
    {page==="disputes"&&<Disputes period={period} rows={rows}/>}
    {page==="standards"&&<Standards standards={standards} tiers={tiers}/>}
  </div>;
}

function Stats({totals}:{totals:{proposed:number;final:number;pending:number;caps:number}}){return <div className="assessment-stats"><div><span>Proposed</span><strong>{money(totals.proposed)}</strong></div><div><span>Reviewed total</span><strong>{money(totals.final)}</strong></div><div><span>Pending review</span><strong>{totals.pending}</strong></div><div><span>CAPs required</span><strong>{totals.caps}</strong></div></div>}
function ScoreTable({rows,status,busy,onDetail}:{rows:PeriodKpiAssessment[];status:AssessmentPeriodStatus;busy:boolean;onDetail:(r:PeriodKpiAssessment)=>void}){if(!rows.length)return <Empty>Compute this Assessment Period to generate its scored performance standards.</Empty>;const heading=reviewDisplay(status,rows[0]).heading;return <div className="assessment-table-wrap"><table className="data"><thead><tr><th>Performance standard</th><th>Metric / target</th><th>Outcome</th><th>Occurrences</th><th>Proposed</th><th>{heading}</th></tr></thead><tbody>{rows.map(r=>{const outcome=r.assessment_outcome==="not_assessable"?"Not Assessable":r.tier_label;return <tr key={r.id} className="assessment-clickable" onClick={()=>!busy&&onDetail(r)}><td><strong>{r.name}</strong><small>{r.priority} · {r.standard_type}</small></td><td>{r.metric_display}<small>{r.target_display||"Target not available"}</small></td><td><span className={`assessment-tier ${r.tier_label}`}>{outcome}</span></td><td>{r.occurrence_count}</td><td>{money(r.proposed_amount)}</td><td>{reviewDisplay(status,r).value}</td></tr>})}</tbody></table></div>}
function KpiDetail({row,occurrences}:{row:PeriodKpiAssessment;occurrences:ComplianceOccurrence[]}){return <div className="assessment-detail"><div><h3>{row.name}</h3><p>{row.metric_display} against {row.target_display||"the configured target"}</p></div><div className="assessment-calculation"><span>Base<strong>{money(row.base_amount)}</strong></span><b>−</b><span>Relief<strong>{money(row.relief_amount)}</strong></span><b>×</b><span>Escalation<strong>{row.escalation_multiplier??1}</strong></span><b>=</b><span>Proposed<strong>{money(row.proposed_amount)}</strong></span></div><p>Data completeness: {row.data_completeness_pct??0}% · Consecutive months below: {row.consecutive_months_below??0}</p><h4>Underlying observations</h4>{occurrences.length?<ul>{occurrences.map(o=><li key={o.id}>{formatDate(o.service_date)}: {o.description} ({o.review_status})</li>)}</ul>:<Empty>No occurrence observations support this KPI.</Empty>}</div>}
function Evidence({assessment}:{assessment:PeriodKpiAssessment}){const [records,setRecords]=useState<AssessmentEvidence[]>([]),[busy,setBusy]=useState(false);const load=useCallback(()=>api.getAssessmentEvidence(assessment.id).then(result=>setRecords(result.evidence)),[assessment.id]);useEffect(()=>{void load()},[load]);async function upload(file:File){setBusy(true);try{const target=await api.getAssessmentEvidenceUploadUrl(assessment.id,file.name);const uploaded=await fetch(target.upload_url,{method:"PUT",headers:{"x-ms-blob-type":"BlockBlob","content-type":file.type||"application/octet-stream"},body:file});if(!uploaded.ok)throw new Error("Evidence upload failed");const digest=await crypto.subtle.digest("SHA-256",await file.arrayBuffer());const hash=Array.from(new Uint8Array(digest),byte=>byte.toString(16).padStart(2,"0")).join("");await api.createAssessmentEvidence({assessment_id:assessment.id,blob_path:target.blob_path,content_type:file.type||"application/octet-stream",file_size_bytes:file.size,content_sha256:hash,visibility:"contractor",caption:file.name,supersedes_id:records[0]?.id});await load()}finally{setBusy(false)}}return <section className="assessment-card"><div className="assessment-section-head"><div><h4>Assessment Evidence</h4><p>Immutable, content-hashed Contractor Evidence supporting this Assessment Item.</p></div><label className="btn-primary">{busy?"Uploading…":"Add evidence version"}<input type="file" hidden disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file)void upload(file)}}/></label></div>{records.length?<ul>{records.map(record=><li key={record.id}>{record.caption??"Evidence"} · {record.visibility} · <code>{record.content_sha256.slice(0,12)}…</code></li>)}</ul>:<Empty>No evidence versions are attached.</Empty>}</section>}
// Which observation an occurrence came from, in words a reviewer can act on.
// The source_ref is a machine key the poll and the intake both build; showing
// it raw ("FixedRouteDepartures:avail_pullout:20260904|1305|2") tells a reader
// nothing about which module to open or what to search for there.
export function occurrenceSourceLabel(sourceRef: string | null | undefined): { module: string; reference: string; to: string } | null {
  if (!sourceRef) return null;
  const [table, rest] = [sourceRef.slice(0, sourceRef.indexOf(":")), sourceRef.slice(sourceRef.indexOf(":") + 1)];
  const tail = rest.slice(rest.indexOf(":") + 1);
  if (table === "MonitoredMissedTrips") {
    const [trip, date] = tail.split("|");
    return { module: "Missed Trips", reference: `Trip ${trip}${date ? ` · ${formatDate(date)}` : ""}`, to: "/compliance" };
  }
  if (table === "FixedRouteDepartures") {
    const [date, block, run] = tail.split("|");
    return { module: "Garage Departures · Fixed Route", reference: `Block ${block}/${run}${date ? ` · ${formatDate(date)}` : ""}`, to: "/compliance" };
  }
  if (table === "OnDemandDepartures") return { module: "Garage Departures · On-Demand", reference: `Duty ${tail}`, to: "/compliance" };
  return { module: table, reference: tail, to: "/compliance" };
}

function Occurrences({rows,periodSelected,busy,onReview,onAmount}:{rows:ComplianceOccurrence[];periodSelected:boolean;busy:boolean;onReview:(o:ComplianceOccurrence,s:"candidate"|"confirmed"|"dismissed",a:"contractor_error"|"excusable"|"mvta_directed"|"undetermined",reason?:string)=>void;onAmount:(o:ComplianceOccurrence,amount:number,note:string)=>void}){const {prompt}=useAppDialog();const dismiss=async(o:ComplianceOccurrence)=>{const reason=await prompt({title:"Dismiss occurrence",label:"Dismissal reason",confirmLabel:"Dismiss occurrence",multiline:true,required:true});if(reason)onReview(o,"dismissed","undetermined",reason)};
// Some penalties are a range, not a number - damage reimbursement runs
// $2,500-$10,000 - so the contract sets the bounds and a reviewer sets the
// figure on the facts. Recorded with a reason, because it is a judgement, and
// the month is not complete while any confirmed occurrence still wants one.
const setAmount=async(o:ComplianceOccurrence)=>{const raw=await prompt({title:`Penalty amount for ${o.standard_name}`,description:`The contract sets this between ${money(o.penalty_amount_min??0)} and ${money(o.penalty_amount_max??0)}. Enter the amount and what it rests on.`,label:"Amount and reason, e.g. 4200 — body shop estimate 2026-088",confirmLabel:"Record amount",required:true});if(!raw)return;const match=/^\s*\$?([0-9]+(?:\.[0-9]{1,2})?)\s*[—:-]?\s*(.*)$/.exec(raw);if(!match||!match[2].trim())return;onAmount(o,Number(match[1]),match[2].trim())};
const ranged=(o:ComplianceOccurrence)=>o.penalty_amount_min!==null&&o.penalty_amount_min!==undefined&&o.penalty_amount_max!==null&&o.penalty_amount_max!==undefined;
const awaiting=rows.filter(o=>o.review_status==="confirmed"&&ranged(o)&&(o.assessed_amount===null||o.assessed_amount===undefined));
return <section><div className="assessment-section-head"><div><h3>Occurrence Log</h3><p>{periodSelected?"Showing the selected Assessment Period.":"Showing recent occurrences for the Agreement contractor."}</p></div>{awaiting.length>0&&<span className="assessment-status stale">{awaiting.length} awaiting an amount</span>}</div>{awaiting.length>0&&<div className="assessment-warning">{awaiting.length} confirmed {awaiting.length===1?"occurrence carries":"occurrences carry"} a penalty the contract states as a range. The month cannot be read as complete until a reviewer records each figure.</div>}{!rows.length?<Empty>No occurrences are currently recorded.</Empty>:<div className="assessment-table-wrap"><table className="data"><thead><tr><th>Date</th><th>Contractor / KPI</th><th>Description</th><th>Observed in</th><th>Status</th><th>Attribution</th><th>Amount</th><th>Review</th></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td>{formatDate(o.service_date)}</td><td>{o.contractor_name}<small>{o.standard_name}</small></td><td>{o.description}</td><td>{(()=>{const source=occurrenceSourceLabel(o.source_ref);return source?<><Link to={source.to}>{source.module}</Link><small className="mono-ref">{source.reference}</small></>:<small>Entered by hand</small>})()}</td><td>{o.review_status}</td><td>{o.attribution}</td><td>{ranged(o)?(o.assessed_amount===null||o.assessed_amount===undefined?<button disabled={busy} onClick={()=>void setAmount(o)}>Set amount…</button>:<><strong>{money(o.assessed_amount)}</strong><small>{o.assessed_by}</small></>):<small>—</small>}</td><td><button disabled={busy||o.review_status==="confirmed"} onClick={()=>onReview(o,"confirmed","contractor_error")}>Confirm</button><button disabled={busy||o.review_status==="dismissed"} onClick={()=>void dismiss(o)}>Dismiss</button></td></tr>)}</tbody></table></div>}</section>}
function Metrics({rows,standards,period,busy,onSave}:{rows:ManualMetricEntry[];standards:ContractorPerformanceStandard[];period:AssessmentPeriod|undefined;busy:boolean;onSave:(id:string,value:number,note:string)=>void}){const manual=standards.filter(s=>s.standard_type==="threshold"&&isHandEntered(s.measurement_source));const [standard,setStandard]=useState(""),[value,setValue]=useState(""),[note,setNote]=useState("");return <section><div className="assessment-section-head"><div><h3>Monthly Metrics</h3><p>Enter governed values for KPIs without an automated feed.</p></div></div>{period&&<div className="assessment-entry"><label><span>Performance standard</span><select value={standard} onChange={e=>setStandard(e.target.value)}><option value="">Select manual KPI</option>{manual.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label><span>Metric value</span><input type="number" placeholder="Enter value" value={value} onChange={e=>setValue(e.target.value)}/></label><label className="assessment-entry-note"><span>Source note</span><input placeholder="Describe the source of record" value={note} onChange={e=>setNote(e.target.value)}/></label><button className="btn-primary" disabled={busy||!standard||!value||!note.trim()} onClick={()=>{onSave(standard,Number(value),note);setValue("");setNote("")}}>Save metric</button></div>}{!period&&<div className="assessment-warning">Select an Assessment Period to enter a metric.</div>}{!rows.length?<Empty>No current manual metrics for this context.</Empty>:<div className="assessment-table-wrap"><table className="data"><thead><tr><th>Month</th><th>KPI</th><th>Value</th><th>Source</th><th>Entered by</th></tr></thead><tbody>{rows.map(m=><tr key={m.id}><td>{formatMonth(m.service_month)}</td><td>{m.standard_name}</td><td>{m.metric_value}</td><td>{m.source_note}</td><td>{m.entered_by}</td></tr>)}</tbody></table></div>}</section>}
function ManagerReview({period,rows,totals,busy,onReview,onCompute,onFinalize}:{period:AssessmentPeriod|undefined;rows:PeriodKpiAssessment[];totals:{final:number;pending:number};busy:boolean;onReview:(r:PeriodKpiAssessment,a:"confirmed"|"adjusted"|"waived",amount?:number,reason?:string)=>void;onCompute:()=>void;onFinalize:()=>void}){const {prompt}=useAppDialog();const adjust=async(r:PeriodKpiAssessment)=>{const amount=await prompt({title:"Recommend adjustment",label:"Recommended amount",defaultValue:String(r.proposed_amount),confirmLabel:"Continue",required:true});const reason=await prompt({title:"Explain adjustment",label:"Adjustment reason",confirmLabel:"Recommend adjustment",multiline:true,required:true});if(amount!==null&&reason)onReview(r,"adjusted",Number(amount),reason)};const waive=async(r:PeriodKpiAssessment)=>{const reason=await prompt({title:"Recommend waiver",label:"Waiver reason",confirmLabel:"Recommend waiver",multiline:true,required:true});if(reason)onReview(r,"waived",0,reason)};if(!period)return <Empty>Select an Assessment Period to begin review.</Empty>;return <section><div className="assessment-section-head"><div><h3>Assessment Review</h3><p>Automation calculates a Proposed Penalty; a reviewer recommends treatment before a separate Issuing Authority finalizes it.</p></div><div><button disabled={busy||!["open","stale","reopened"].includes(period.status)} onClick={onCompute}>{period.status==="stale"?"Recompute":"Compute"}</button> <button disabled={busy||period.status!=="in_validation"||totals.pending>0} onClick={onFinalize}>Finalize {money(totals.final)}</button></div></div>{!rows.length?<Empty>Compute the period to create its review queue.</Empty>:rows.map(r=><div className="assessment-review-row" key={r.id}><div><strong>{r.name}</strong><small>{r.metric_display} · proposed {money(r.proposed_amount)}</small></div><span>{(()=>{const d=reviewDisplay(period.status,r);return `${d.heading}: ${d.value}`})()}</span><button disabled={busy||period.status!=="in_review"} onClick={()=>onReview(r,"confirmed")}>Recommend confirmation</button><button disabled={busy||period.status!=="in_review"} onClick={()=>void adjust(r)}>Recommend adjustment</button><button disabled={busy||period.status!=="in_review"} onClick={()=>void waive(r)}>Recommend waiver</button></div>)}</section>}
function Caps({rows,period}:{rows:PeriodKpiAssessment[];period:AssessmentPeriod|undefined}){const [records,setRecords]=useState<AssessmentCap[]>([]);useEffect(()=>{if(!period){setRecords([]);return}void api.getAssessmentCaps(period.id).then(result=>setRecords(result.caps))},[period]);const pending=rows.filter(r=>r.cap_required||r.tier_label==="tier2");return <section><div className="assessment-section-head"><div><h3>Corrective Action Plans</h3><p>CAP Determinations remain independent of Monetary Adjustments and Penalty Waivers.</p></div></div>{records.map(cap=><div className="assessment-card" key={cap.id}><strong>{cap.standard_name}</strong><p>{cap.trigger_reason} · due {formatDate(cap.due_at)}</p><span className="assessment-tier tier2">{cap.status}</span></div>)}{!records.length&&pending.map(row=><div className="assessment-card" key={row.id}><strong>{row.name}</strong><p>{row.cap_reason||`${row.tier_label} outcome requires CAP review.`}</p><span className="assessment-tier tier2">Pending issuance</span></div>)}{!records.length&&!pending.length&&<Empty>No CAP Determinations exist for the selected Assessment Period.</Empty>}</section>}
function Disputes({period,rows}:{period:AssessmentPeriod|undefined;rows:PeriodKpiAssessment[]}){const [records,setRecords]=useState<AssessmentDispute[]>([]);useEffect(()=>{if(!period){setRecords([]);return}void api.getAssessmentDisputes(period.id).then(result=>setRecords(result.disputes))},[period]);if(!period)return <Empty>Select an Assessment Period to view disputes.</Empty>;return <section><div className="assessment-section-head"><div><h3>Assessment Disputes</h3><p>Disputes identify the specific Assessment Items challenged; unchallenged items remain final.</p></div></div>{records.map(dispute=><div className="assessment-card" key={dispute.id}><strong>Final Assessment v{dispute.report_version}</strong><p>{dispute.item_count} item(s) · {dispute.basis}</p><span>{dispute.outcome??dispute.status}</span></div>)}{!records.length&&<Empty>{period.status==="issued"&&rows.length?"No disputes have been recorded for this Final Assessment.":"Disputes become available after Final Assessment issuance."}</Empty>}</section>}
// Read-only mirror of the catalog. Editing lives in Administration >
// Performance Standards: changing a band is contract governance, and every
// role that can open this module can read a scorecard but must not be able to
// change what produced it.
function bandText(standard:ContractorPerformanceStandard,tier:ContractorStandardTier){const ratio=standard.unit_label==="percent"||standard.unit_label==="%";const show=(value:number|null)=>value===null?"":String(ratio?Number((value*100).toFixed(4)):value);const low=show(tier.bound_low),high=show(tier.bound_high);const band=low||high?` ${low||"–"}…${high||"–"}`:"";const charge=tier.penalty_basis==="none"?"no penalty":`${money(Number(tier.penalty_amount))} ${tier.penalty_basis.replaceAll("_"," ")}`;return `${tier.tier_label}${band}: ${charge}${tier.triggers_cap?" · CAP":""}`}
function Standards({standards,tiers}:{standards:ContractorPerformanceStandard[];tiers:ContractorStandardTier[]}){const isAdmin=useAuth().roles.includes("OCC.Admin");return <section><div className="assessment-section-head"><div><h3>Standards</h3><p>The performance standards catalog and the tier bands that govern scoring. {isAdmin?<>Edit these under <Link to="/admin/performance-standards">Administration › Performance Standards</Link>.</>:"Changing a band or an Agreement assignment requires Administrator access."}</p></div><span>{standards.length} standards · {tiers.length} tiers</span></div><div className="assessment-table-wrap"><table className="data"><thead><tr><th>Code / standard</th><th>Type</th><th>Priority</th><th>Scored</th><th>Source</th><th>Owner</th><th>Tier bands</th></tr></thead><tbody>{standards.map(s=><tr key={s.id}><td><strong>{s.code}</strong><small>{s.name}</small></td><td>{s.standard_type}</td><td>{s.priority}</td><td>{s.is_scored?"Yes":"No"}</td><td>{sourceLabel(s.measurement_source,s.source_system)}{isAutomated(s.measurement_source)&&!s.resolver_key?<small> · no resolver</small>:null}</td><td>{s.assigned_to??"—"}<small>{s.responsible_team??""}</small></td><td>{tiers.filter(t=>t.standard_id===s.id&&!t.agreement_id&&!t.effective_end_date).sort((a,b)=>a.tier_order-b.tier_order).map(t=>bandText(s,t)).join(" · ")||"—"}</td></tr>)}</tbody></table></div></section>}

function ContractorSetup({contractors,canEdit,busy,onSave}:{contractors:ContractorRecord[];canEdit:boolean;busy:boolean;onSave:(id:string,input:{name:string;contract_start_date:string;contract_end_date:string|null;is_active:boolean})=>void}){
  const [selected,setSelected]=useState("new"),[name,setName]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[active,setActive]=useState(true);
  useEffect(()=>{const c=contractors.find(x=>x.id===selected);setName(c?.name??"");setStart(inputDate(c?.contract_start_date));setEnd(inputDate(c?.contract_end_date));setActive(c?.is_active??true)},[selected,contractors]);
  return <section className="contractor-setup"><div className="assessment-section-head"><div><span className="assessment-eyebrow">Administration</span><h3>Agreement contractor</h3><p>Maintain the sole Assessment Contractor for this Agreement.</p></div></div>{!canEdit&&<div className="assessment-warning">Administrator access is required to change the Agreement contractor.</div>}<div className="contractor-form"><label><span>Contractor record</span><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="new">Add the Agreement contractor</option>{contractors.map(c=><option key={c.id} value={c.id}>{c.name}{c.is_active?"":" (inactive)"}</option>)}</select></label><label><span>Contractor name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Legal or operating name" disabled={!canEdit}/></label><label><span>Agreement start date</span><input type="date" value={start} onChange={e=>setStart(e.target.value)} disabled={!canEdit}/><small>{start?formatDate(start):"MM/DD/YYYY"}</small></label><label><span>Agreement end date</span><input type="date" value={end} onChange={e=>setEnd(e.target.value)} disabled={!canEdit}/><small>{end?formatDate(end):"Optional · MM/DD/YYYY"}</small></label><label className="contractor-active"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)} disabled={!canEdit}/><span>Current Agreement contractor</span></label><button className="btn-primary" disabled={!canEdit||busy||!name.trim()||!start} onClick={()=>onSave(selected==="new"?crypto.randomUUID():selected,{name:name.trim(),contract_start_date:start.replace(/-/g,""),contract_end_date:end?end.replace(/-/g,""):null,is_active:active})}>{selected==="new"?"Add contractor":"Save contractor"}</button></div>{contractors.length>0&&<div className="contractor-list">{contractors.map(c=><div key={c.id}><div><strong>{c.name}</strong><span>{c.is_active?"Current":"Historical"}</span></div><p>{formatDate(c.contract_start_date)} – {c.contract_end_date?formatDate(c.contract_end_date):"Ongoing"}</p></div>)}</div>}</section>
}
