import { Fragment, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { FALLBACK_TIER_LABELS, describeBand, isAutomated, optionsFor, sourceLabel, type VocabularyOption } from "../../performanceStandardsVocabulary.js";
import { currentMonth, lifecycleStages, nextAction, occurrencesNeedingAmount, outstandingItems, periodFor, reviewProgress, statusPill, stepMonth } from "./glance.js";
import { groupByCategory, type CategoryGroup } from "./categoryGroups.js";
import { metricsChecklist, type MetricsChecklist } from "./metricsChecklist.js";
import { metricText, targetText } from "./scorecardDisplay.js";
import type { AgreementStandardAssignment, AssessmentDispute, AssessmentEvidence, AssessmentPeriod, AssessmentPeriodStatus, ComplianceOccurrence, ContractorPerformanceStandard, ContractorRecord, ContractorStandardTier, ExcusableDelayClaim, ManualMetricEntry, OccurrenceAttribution, OccurrenceReviewStatus, PerformanceAgreementRecord, PeriodKpiAssessment, ReferenceValue } from "@mvta/shared";
import { api } from "../../../config.js";
import { useAuth } from "../../../auth/AuthContext.js";
import { ReportWorkflow } from "./ReportWorkflow.js";
import { Caps } from "./Caps.js";
import { Relief } from "./Relief.js";
import { OpenInputs } from "./OpenInputs.js";
import { History } from "./History.js";
import { Empty, formatDate, formatMonth, money } from "./assessmentFormat.js";
import { usePeriodRows } from "./usePeriodRows.js";
import { reviewDisplay, reviewHeading } from "./reviewDisplay.js";
import { useAppDialog } from "../../../components/AppDialog.js";
import "./assessment.css";

// Six sections. A standard's detail is reached from its scorecard row, not a
// tab of its own; the report and its disputes are one issuance flow; and the
// read-only standards mirror is a link at the end of the bar rather than a
// section of the month. Each section carries a count of what is outstanding
// in it, so the bar reads as a to-do list as much as a menu.
type Page = "scorecard"|"detail"|"occurrences"|"metrics"|"review"|"caps"|"issuance"|"history"|"standards";
type NavKey = Exclude<Page,"detail"|"standards">;
const NAV: {key:NavKey;label:string;hot?:boolean}[] = [
  {key:"scorecard",label:"Scorecard"},{key:"occurrences",label:"Occurrences"},{key:"metrics",label:"Monthly metrics",hot:true},
  {key:"review",label:"Review",hot:true},{key:"caps",label:"CAPs"},{key:"issuance",label:"Issuance"},{key:"history",label:"History"},
];
const externalIcon=<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M14 4h6v6"/><path d="M20 4 10 14"/><path d="M18 14v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h5"/></svg>;
const inputDate=(value:string|null|undefined)=>{const d=value?.replace(/\D/g,"")??"";return d.length===8?`${d.slice(0,4)}-${d.slice(4,6)}-${d.slice(6,8)}`:""};

export function AssessmentModule(){
  const {roles}=useAuth(),isAdmin=roles.includes("OCC.Admin");
  const navigate=useNavigate();
  const [page,setPage]=useState<Page>("scorecard"),[periods,setPeriods]=useState<AssessmentPeriod[]>([]),[contractors,setContractors]=useState<ContractorRecord[]>([]),[standards,setStandards]=useState<ContractorPerformanceStandard[]>([]),[tiers,setTiers]=useState<ContractorStandardTier[]>([]),[occurrences,setOccurrences]=useState<ComplianceOccurrence[]>([]),[metrics,setMetrics]=useState<ManualMetricEntry[]>([]),[contractorId,setContractorId]=useState(""),[agreements,setAgreements]=useState<PerformanceAgreementRecord[]>([]),[referenceValues,setReferenceValues]=useState<ReferenceValue[]>([]),[assignments,setAssignments]=useState<AgreementStandardAssignment[]>([]),[month,setMonth]=useState(currentMonth()),[showContractors,setShowContractors]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[tableReady,setTableReady]=useState(true);
  // The first load lands on the most recent period; after that the contractor
  // and month the reader chose stay put across reloads.
  const seeded=useRef(false);
  const load=useCallback(async()=>{try{setError("");const [p,c,s,a,v]=await Promise.all([api.getAssessmentPeriods(),api.getContractors(),api.getPerformanceStandards(),api.getPerformanceAgreements().catch(()=>({agreements:[] as PerformanceAgreementRecord[]})),api.getReferenceValues().catch(()=>({values:[] as ReferenceValue[]}))]);setPeriods(p.periods);setContractors(c.contractors);setStandards(s.standards);setTiers(s.tiers??[]);setAssignments(s.assignments??[]);setAgreements(a.agreements);setReferenceValues(v.values??[]);setTableReady(p.diagnostics.table_ready&&c.diagnostics.table_ready&&s.diagnostics.table_ready);if(!seeded.current){seeded.current=true;const first=p.periods[0];if(first){setContractorId(first.contractor_id);setMonth(first.service_month)}else setContractorId(c.contractors.find(x=>x.is_active)?.id||"")}}catch(e){setError(e instanceof Error?e.message:"Unable to load assessment workspace")}},[]);
  useEffect(()=>{void load()},[load]);
  const [refreshKey,setRefreshKey]=useState(0);
  const period=periodFor(periods,contractorId,month),selected=period?.id??"",agreement=agreements.find(a=>a.contractor_id===contractorId&&a.is_active);
  const {rows,detailId,setDetailId,error:rowsError}=usePeriodRows(api.getPeriodAssessments,selected,refreshKey);
  const activeContractors=contractors.filter(c=>c.is_active),detail=rows.find(r=>r.id===detailId),periodOccurrences=period?occurrences.filter(o=>o.contractor_id===period.contractor_id&&o.service_date.startsWith(period.service_month)):occurrences,periodMetrics=period?metrics.filter(m=>m.contractor_id===period.contractor_id&&m.service_month===period.service_month):metrics;
  const [claims,setClaims]=useState<ExcusableDelayClaim[]>([]),[claimsTick,setClaimsTick]=useState(0);
  useEffect(()=>{if(!period){setClaims([]);return}let active=true;api.getExcusableDelayClaims(period.contractor_id,period.service_month).then(r=>{if(active)setClaims(r.claims.filter(c=>c.status==="approved"))}).catch(()=>{if(active)setClaims([])});return()=>{active=false}},[period,claimsTick]);
  // The month's own rows, filtered on the request (H2) rather than fetched
  // whole and sifted here; with no period selected, a recent capped set.
  useEffect(()=>{let active=true;const scope=period?{contractor_id:period.contractor_id,service_month:period.service_month}:{};Promise.all([api.getComplianceOccurrences({...scope,limit:period?2000:200}),api.getManualMetrics({...scope,limit:period?1000:200})]).then(([o,m])=>{if(active){setOccurrences(o.occurrences);setMetrics(m.metrics)}}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Unable to load the month's inputs")});return()=>{active=false}},[period,refreshKey]);
  const totals=useMemo<AssessmentTotals>(()=>({proposed:rows.reduce((s,r)=>s+Number(r.proposed_amount||0),0),final:rows.reduce((s,r)=>s+Number(r.recommended_amount??r.final_amount??0),0),occurrences:rows.reduce((s,r)=>s+Number(r.occurrence_count||0),0),pending:rows.filter(r=>!r.recommended_action).length,caps:rows.filter(r=>r.cap_required||r.tier_label==="tier2").length}),[rows]);
  const vocab=useMemo(()=>({tiers:optionsFor(referenceValues,"tier_label",FALLBACK_TIER_LABELS),categories:optionsFor(referenceValues,"category",[])}),[referenceValues]);
  const openCatalog=()=>isAdmin?navigate("/admin/performance/standards"):setPage("standards");
  const checklist=useMemo<MetricsChecklist>(()=>period?metricsChecklist(rows,standards,periodMetrics,agreement?new Set(assignments.filter(a=>a.agreement_id===agreement.id).map(a=>a.standard_id)):undefined):{scored:[],unscored:[],entered:0},[period,rows,standards,periodMetrics,agreement,assignments]);
  // Figure and target in words, from the row when the compute step wrote them so and from the catalog otherwise.
  const catalogLadder=useCallback((standardId:string)=>tiers.filter(t=>t.standard_id===standardId&&!t.agreement_id&&!t.effective_end_date).sort((a,b)=>a.tier_order-b.tier_order),[tiers]);
  const display=useMemo(()=>new Map(rows.map(r=>{const standard=standards.find(x=>x.id===r.standard_id);return [r.id,{metric:metricText(r,standard),target:targetText(r,standard,catalogLadder(r.standard_id))}]})),[rows,standards,catalogLadder]);
  const groups=useMemo(()=>groupByCategory(rows,r=>standards.find(s=>s.id===r.standard_id)?.category,vocab.categories),[rows,standards,vocab.categories]);
  const barProgress=reviewProgress(rows);
  const counts:Record<NavKey,number>={scorecard:0,occurrences:period?occurrencesNeedingAmount(periodOccurrences):0,metrics:checklist.scored.length-checklist.entered,review:barProgress.total-barProgress.reviewed,caps:totals.caps,issuance:0,history:0};
  // Rows are reloaded by the period loader, keyed on refreshKey, so an
  // action's refresh can never land on a period selected after it started.
  async function act(action:()=>Promise<unknown>){setBusy(true);setError("");try{await action();await load();setRefreshKey(k=>k+1)}catch(e){setError(e instanceof Error?e.message:"Action failed")}finally{setBusy(false)}}
  if(!tableReady)return <div className="concept-banner">Performance Assessment database objects are not ready. Apply migration 030, then migration 031.</div>;
  return <div className="assessment-module">
    {showContractors&&<ContractorSetup contractors={contractors} canEdit={isAdmin} busy={busy} onSave={(id,input)=>void act(()=>api.putContractor(id,input))}/>}
    {!activeContractors.length&&!showContractors&&<div className="assessment-warning"><strong>Setup required:</strong> no active contractor is configured. <button className="assessment-link-button" onClick={()=>setShowContractors(true)}>Set up a contractor</button> to begin.</div>}
    {(error||rowsError)&&<div className="assessment-error">{error||rowsError}</div>}
    <Glance contractors={activeContractors} contractorId={contractorId} onContractor={setContractorId} month={month} onMonth={setMonth} period={period} agreement={agreement} rows={rows} occurrences={period?periodOccurrences:[]} totals={totals} missingFigures={checklist.scored.length-checklist.entered} busy={busy} manageOpen={showContractors} onManage={()=>setShowContractors(v=>!v)} onOpen={()=>void act(()=>api.openAssessmentPeriod(contractorId,month))} onCompute={()=>period&&void act(()=>api.computeAssessmentPeriod(period.id))} onFinalize={()=>period&&void act(()=>api.finalizeAssessmentPeriod(period.id))} onGo={setPage}/>
    <nav className="assessment-nav" aria-label="Assessment sections">
      {NAV.map(n=>{const count=counts[n.key],active=page===n.key||(n.key==="scorecard"&&page==="detail");return <button key={n.key} type="button" className={active?"active":""} aria-current={active?"page":undefined} onClick={()=>setPage(n.key)}>{n.label}{count>0&&<span className={`assessment-nav-count${n.hot?" hot":""}`}>{n.key==="metrics"?`${count} missing`:count}</span>}</button>})}
      <span className="assessment-nav-spacer"/>
      {isAdmin?<Link className="assessment-nav-link" to="/admin/performance/standards">Standards catalog {externalIcon}</Link>:<button type="button" className={`assessment-nav-link${page==="standards"?" active":""}`} onClick={()=>setPage("standards")}>Standards catalog</button>}
    </nav>
    {page==="scorecard"&&(!period?<Empty>Open this Assessment Period to view its scorecard.</Empty>:<ScoreTable rows={rows} groups={groups} totals={totals} display={display} status={period.status} tiers={vocab.tiers} busy={busy} onDetail={r=>{setDetailId(r.id);setPage("detail")}} onEnterFigure={()=>setPage("metrics")}/>)}
    {page==="detail"&&(!period?<Empty>Open this Assessment Period, then choose a standard from its scorecard.</Empty>:<div className="assessment-stack">
      <div className="assessment-detail-bar"><button type="button" className="assessment-crumb" onClick={()=>setPage("scorecard")}>{chevron("left")} Back to scorecard</button><select aria-label="Standard" value={detailId} onChange={e=>setDetailId(e.target.value)}>{rows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></div>
      {detail?<StandardDetail row={detail} period={period} standard={standards.find(s=>s.id===detail.standard_id)} ladder={tiers.filter(t=>t.standard_id===detail.standard_id&&!t.agreement_id&&!t.effective_end_date).sort((a,b)=>a.tier_order-b.tier_order)} occurrences={periodOccurrences.filter(o=>o.standard_id===detail.standard_id)} vocab={vocab} busy={busy} onReview={(r,a,amount,reason)=>void act(()=>api.reviewPeriodAssessment(r.id,a,amount,reason))} onGo={setPage}/>:<Empty>Compute this month to produce detail for its standards.</Empty>}
    </div>)}
    {page==="occurrences"&&<><Occurrences rows={periodOccurrences} periodSelected={Boolean(period)} busy={busy} claims={claims} onAmount={(o,amount,note)=>void act(()=>api.setOccurrenceAssessedAmount(o.id,amount,note))} onReview={(o,status,attribution,reason)=>void act(()=>api.reviewComplianceOccurrence(o.id,status,attribution,reason))} onRelief={(o,reliefId)=>void act(()=>api.linkOccurrenceRelief(o.id,o.review_status as OccurrenceReviewStatus,o.attribution as OccurrenceAttribution,reliefId))}/><Relief period={period} onChanged={()=>{void load();setRefreshKey(k=>k+1);setClaimsTick(t=>t+1)}}/></>}
    {page==="metrics"&&<><OpenInputs period={period}/><Metrics checklist={checklist} computed={rows.length>0} period={period} busy={busy} onCatalog={openCatalog} onSave={(standard_id,value,note)=>period&&void act(()=>api.putManualMetric({standard_id,contractor_id:period.contractor_id,service_month:period.service_month,metric_value:value,source_note:note}))}/></>}
    {page==="review"&&<ManagerReview period={period} rows={rows} totals={totals} busy={busy} onReview={(r,a,amount,reason)=>void act(()=>api.reviewPeriodAssessment(r.id,a,amount,reason))} onCompute={()=>period&&void act(()=>api.computeAssessmentPeriod(period.id))} onFinalize={()=>period&&void act(()=>api.finalizeAssessmentPeriod(period.id))}/>}
    {page==="caps"&&<Caps rows={rows} period={period}/>}
    {page==="issuance"&&<div className="assessment-stack"><ReportWorkflow period={period} busy={busy} act={act}/><Disputes period={period} rows={rows}/></div>}
    {page==="history"&&<History period={period}/>}
    {page==="standards"&&<Standards standards={standards} tiers={tiers}/>}
  </div>;
}

// One contractor, one month, at a glance: where the month is, what it adds
// up to, what is still in the way, and the one thing it needs next. The
// contractor and month ARE the selection - a month that has no period yet
// shows as "Not opened" with opening it as the action, so there is one way to
// pick a month rather than a picker to open one and a select to find it.
const chevron=(direction:"left"|"right")=><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={direction==="left"?"m15 6-6 6 6 6":"m9 6 6 6-6 6"}/></svg>;
const check=<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg>;
function Glance({contractors,contractorId,onContractor,month,onMonth,period,agreement,rows,occurrences,totals,missingFigures,busy,manageOpen,onManage,onOpen,onCompute,onFinalize,onGo}:{contractors:ContractorRecord[];contractorId:string;onContractor:(id:string)=>void;month:string;onMonth:(month:string)=>void;period:AssessmentPeriod|undefined;agreement:PerformanceAgreementRecord|undefined;rows:PeriodKpiAssessment[];occurrences:ComplianceOccurrence[];totals:AssessmentTotals;missingFigures:number;busy:boolean;manageOpen:boolean;onManage:()=>void;onOpen:()=>void;onCompute:()=>void;onFinalize:()=>void;onGo:(page:Page)=>void}){
  const status=period?.status??null,stages=lifecycleStages(status),pill=statusPill(status),action=nextAction(status,totals.pending),items=outstandingItems(rows,occurrences,missingFigures),progress=reviewProgress(rows);
  const run=()=>{if(action.kind==="open")onOpen();else if(action.kind==="compute")onCompute();else if(action.kind==="finalize")onFinalize();else onGo(action.page)};
  const reference=agreement?[agreement.contract_number,agreement.exhibit_reference].filter(Boolean).join(" · "):"";
  return <section className="assessment-glance" aria-label="Assessment month at a glance">
    <div className="assessment-glance-top">
      <div className="assessment-glance-identity">
        <select className="assessment-glance-picker" aria-label="Contractor" value={contractorId} disabled={!contractors.length} onChange={e=>onContractor(e.target.value)}>{!contractors.length&&<option value="">No Assessment Contractor</option>}{contractors.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>
        <span className="assessment-glance-month"><button type="button" aria-label="Previous month" disabled={busy} onClick={()=>onMonth(stepMonth(month,-1))}>{chevron("left")}</button><strong>{formatMonth(month)}</strong><button type="button" aria-label="Next month" disabled={busy} onClick={()=>onMonth(stepMonth(month,1))}>{chevron("right")}</button></span>
        <span className={`pill-sm ${pill.className}`}>{pill.label}</span>
      </div>
      <button className="btn-primary" disabled={busy||!contractorId} onClick={run}>{action.label}</button>
    </div>
    <div className="assessment-glance-meta">
      {reference&&<span>{reference}</span>}
      {period?<><span>{rows.length} standards scored</span><span>{period.computed_revision===null?"Not yet computed":`Computed from input revision ${period.computed_revision}`}{period.computed_revision!==null&&period.input_revision!==period.computed_revision?` · inputs now at ${period.input_revision}`:""}</span></>:contractorId?<span>No assessment has been opened for this month.</span>:null}
      <button type="button" className="assessment-link-button" onClick={onManage}>{manageOpen?"Close contractor setup":"Manage contractors"}</button>
    </div>
    <div className="assessment-glance-bottom">
      <ol className="assessment-lifecycle" aria-label="Lifecycle">{stages.map(s=><li key={s.label} className={s.state} aria-current={s.state==="current"?"step":undefined}><span className="assessment-lifecycle-node" aria-hidden="true">{s.state==="done"?check:null}</span><span>{s.label}</span></li>)}</ol>
      <div className="assessment-figures">
        <div><span>Proposed penalties</span><strong>{money(totals.proposed)}</strong><small>Automation, before review</small></div>
        <div><span>Recommended so far</span><strong>{money(totals.final)}</strong><small>{progress.reviewed} of {progress.total} items reviewed</small></div>
        <div className="assessment-outstanding"><span>Outstanding</span>{items.length?items.map(i=><button type="button" key={i.key} className={i.quiet?"quiet":undefined} onClick={()=>onGo(i.page)}>{i.label}</button>):<small>{rows.length?"Nothing outstanding":period?"Compute the month to score it":"Open the month to begin"}</small>}</div>
      </div>
    </div>
  </section>;
}
// The scorecard reads in the contract's order: grouped by category, the
// categories as Lists orders them, each standard where the period put it.
function ScoreTable({rows,groups,totals,display,status,tiers,busy,onDetail,onEnterFigure}:{rows:PeriodKpiAssessment[];groups:CategoryGroup<PeriodKpiAssessment>[];totals:AssessmentTotals;display:Map<string,{metric:string;target:string}>;status:AssessmentPeriodStatus;tiers:VocabularyOption[];busy:boolean;onDetail:(r:PeriodKpiAssessment)=>void;onEnterFigure:()=>void}){if(!rows.length)return <Empty>Compute this month to score its standards.</Empty>;const heading=reviewHeading(status);return <div className="assessment-table-wrap"><table className="data"><thead><tr><th>Performance standard</th><th>Metric / target</th><th>Outcome</th><th>Occurrences</th><th>Proposed</th><th>{heading}</th><th></th></tr></thead><tbody>{groups.map(group=><Fragment key={group.key||"other"}>{group.label&&<tr className="route-group-header"><td colSpan={7}>{group.label}{group.description&&<span className="muted"> · {group.description}</span>}</td></tr>}{group.items.map(r=>{const outcome=outcomePill(r,tiers);return <tr key={r.id} className="assessment-clickable" onClick={()=>!busy&&onDetail(r)}><td><strong>{r.name}</strong><small>{r.code} · {r.priority==="NA"?"No priority":r.priority}</small></td><td>{display.get(r.id)?.metric??r.metric_display}<small>{display.get(r.id)?.target??r.target_display}</small></td><td><span className={`assessment-tier ${outcome.className}`}>{outcome.label}</span></td><td>{r.occurrence_count}</td><td>{money(r.proposed_amount)}</td><td>{r.assessment_outcome==="not_assessable"?<button type="button" className="assessment-link-button" onClick={e=>{e.stopPropagation();onEnterFigure()}}>Enter figure</button>:reviewCell(reviewDisplay(status,r).value)}</td><td className="assessment-row-chevron">{chevron("right")}</td></tr>})}</Fragment>)}<tr className="assessment-total"><td colSpan={3}>Totals</td><td>{totals.occurrences}</td><td>{money(totals.proposed)}</td><td colSpan={2}>Recommended so far {money(totals.final)}</td></tr></tbody></table></div>}
type Prompt=ReturnType<typeof useAppDialog>["prompt"];
type Recommend=(r:PeriodKpiAssessment,a:"confirmed"|"adjusted"|"waived",amount?:number,reason?:string)=>void;
async function recommendAdjustment(prompt:Prompt,r:PeriodKpiAssessment,onReview:Recommend){const amount=await prompt({title:"Recommend adjustment",label:"Recommended amount",defaultValue:String(r.proposed_amount),confirmLabel:"Continue",required:true});const reason=await prompt({title:"Explain adjustment",label:"Adjustment reason",confirmLabel:"Recommend adjustment",multiline:true,required:true});if(amount!==null&&reason)onReview(r,"adjusted",Number(amount),reason)}
async function recommendWaiver(prompt:Prompt,r:PeriodKpiAssessment,onReview:Recommend){const reason=await prompt({title:"Recommend waiver",label:"Waiver reason",confirmLabel:"Recommend waiver",multiline:true,required:true});if(reason)onReview(r,"waived",0,reason)}
/** What the month adds up to, read once from its rows and shared by the card, the scorecard and the review queue. */
export type AssessmentTotals={proposed:number;final:number;occurrences:number;pending:number;caps:number};
const tierLabel=(tiers:VocabularyOption[],value:string)=>tiers.find(t=>t.value===value)?.label??value;
function outcomePill(row:PeriodKpiAssessment,tiers:VocabularyOption[]):{className:string;label:string}{return row.assessment_outcome==="not_assessable"?{className:"not_assessable",label:"Not assessable"}:{className:row.tier_label,label:tierLabel(tiers,row.tier_label)}}
// The review column as a pill: the recommendation before finalization, the binding decision after, in the same colours the rail uses.
const reviewCell=(value:string)=>{if(value==="—")return <span className="muted">—</span>;const kind=value.startsWith("confirmed")?"pill-success":value.startsWith("adjusted")||value.startsWith("waived")?"pill-accent":"pill-muted";return <span className={`pill-sm ${kind}`}>{value.charAt(0).toUpperCase()+value.slice(1)}</span>};
const reviewPill=(row:PeriodKpiAssessment):{className:string;label:string}=>{switch(row.recommended_action){case "confirmed":return {className:"pill-success",label:"Confirmed"};case "adjusted":return {className:"pill-accent",label:`Adjusted → ${money(row.recommended_amount)}`};case "waived":return {className:"pill-accent",label:"Waived"};default:return {className:"pill-muted",label:"Awaiting your recommendation"}}};
const occurrencePill=(status:string)=>status==="confirmed"?"pill-success":status==="dismissed"?"pill-muted":"pill-warning";
const fileIcon=<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8Z"/><path d="M14 3v5h5"/></svg>;
// One standard in one month: how its figure was produced, the observations
// behind it, and - in the rail - what a reviewer can do about it, what it
// triggers, the evidence, and the facts of the standard itself. Reached from a
// scorecard row; the review actions are the same ones the Review section
// offers, so a reviewer can work either way.
function StandardDetail({row,period,standard,ladder,occurrences,vocab,busy,onReview,onGo}:{row:PeriodKpiAssessment;period:AssessmentPeriod;standard:ContractorPerformanceStandard|undefined;ladder:ContractorStandardTier[];occurrences:ComplianceOccurrence[];vocab:{tiers:VocabularyOption[];categories:VocabularyOption[]};busy:boolean;onReview:Recommend;onGo:(page:Page)=>void}){
  const {prompt}=useAppDialog();
  const outcome=outcomePill(row,vocab.tiers),review=reviewPill(row),canReview=!busy&&period.status==="in_review",capFlagged=Boolean(row.cap_required)||row.tier_label==="tier2";
  const category=standard?.category?vocab.categories.find(c=>c.value===standard.category)?.label??standard.category:null;
  const facts=[standard?.code??row.code,category,row.priority&&row.priority!=="NA"?`${row.priority} priority`:null,standard?.is_safety_critical?"safety-critical":null].filter(Boolean).join(" · ");
  return <div className="assessment-detail">
    <div className="assessment-stack">
      <div className="assessment-detail-head"><div><h3>{row.name}</h3><p>{facts}{facts?" · ":""}{metricText(row,standard)} against {targetText(row,standard,ladder)}</p></div><span className={`assessment-tier ${outcome.className}`}>{outcome.label}</span></div>
      <div className="assessment-calc"><div><span>Base</span><strong>{money(row.base_amount)}</strong></div><b>−</b><div><span>Relief</span><strong>{money(row.relief_amount)}</strong></div><b>×</b><div><span>Escalation</span><strong>{row.escalation_multiplier??1}</strong></div><div className="result"><span>Proposed penalty</span><strong>{money(row.proposed_amount)}</strong></div></div>
      <div className="assessment-glance-meta" style={{margin:0}}><span>Data completeness {row.data_completeness_pct??0}%</span><span>{row.consecutive_months_below?`${row.consecutive_months_below} consecutive ${row.consecutive_months_below===1?"month":"months"} below the standard`:"Not below the standard last month"}</span></div>
      <div className="assessment-section-head"><div><h4 style={{margin:0}}>Observations</h4><p>The occurrences this figure counts. Candidates count until they are dismissed.</p></div>{occurrences.length>0&&<button type="button" className="btn-sm" onClick={()=>onGo("occurrences")}>Open in Occurrences {chevron("right")}</button>}</div>
      {occurrences.length?<div className="assessment-table-wrap"><table className="data"><thead><tr><th>Date</th><th>Description</th><th>Observed in</th><th>Status</th></tr></thead><tbody>{occurrences.map(o=>{const source=occurrenceSourceLabel(o.source_ref);return <tr key={o.id}><td style={{whiteSpace:"nowrap"}}>{formatDate(o.service_date)}</td><td>{o.description}</td><td>{source?<span className="assessment-obs"><Link to={source.to}>{source.module}</Link><small className="mono-ref">{source.reference}</small></span>:<small>Entered by hand</small>}</td><td><span className={`pill-sm ${occurrencePill(o.review_status)}`}>{o.review_status}</span></td></tr>})}</tbody></table></div>:<Empty>{row.standard_type==="threshold"?"A monthly figure, not a count of occurrences.":"No occurrences support this standard this month."}</Empty>}
    </div>
    <aside className="assessment-rail">
      <div className="assessment-rail-card"><h4>Review</h4><p>Automation proposed {money(row.proposed_amount)}. A reviewer recommends treatment; a separate Issuing Authority finalizes.</p><span className={`pill-sm ${review.className}`} style={{justifySelf:"start"}}>{review.label}</span>{row.manager_reason&&<p>{row.manager_reason}</p>}<div className="assessment-rail-actions"><button type="button" className="btn-primary" disabled={!canReview} onClick={()=>onReview(row,"confirmed")}>Recommend confirmation</button><button type="button" className="btn-sm" disabled={!canReview} onClick={()=>void recommendAdjustment(prompt,row,onReview)}>Recommend adjustment…</button><button type="button" className="btn-sm" disabled={!canReview} onClick={()=>void recommendWaiver(prompt,row,onReview)}>Recommend waiver…</button></div>{period.status!=="in_review"&&<p>Recommendations are made while the month is in review.</p>}</div>
      {capFlagged&&<div className="assessment-rail-card"><h4>Corrective action</h4><p>{row.cap_reason||(row.tier_label==="tier2"?"A Tier 2 outcome requires CAP review.":(row.consecutive_months_below??0)>=3?`${row.consecutive_months_below} consecutive months below the standard require a CAP.`:"This outcome requires CAP review.")} A CAP determination stays independent of any adjustment or waiver.</p><div className="assessment-rail-head"><span className="pill-sm pill-warning">CAP flagged</span><button type="button" className="btn-sm" onClick={()=>onGo("caps")}>Open CAPs {chevron("right")}</button></div></div>}
      <EvidenceCard assessment={row}/>
      <div className="assessment-rail-card"><h4>About this standard</h4><dl className="assessment-kv"><dt>Measured</dt><dd>{standard?sourceLabel(standard.measurement_source,standard.source_system):"—"}</dd><dt>Team</dt><dd>{standard?.responsible_team||"—"}</dd><dt>Owner</dt><dd>{standard?.assigned_to||"—"}</dd><dt>Bands</dt><dd>{standard&&ladder.length?<ul className="assessment-band-list">{ladder.map(t=><li key={t.id}><span className={`assessment-tier ${t.tier_label}`}>{tierLabel(vocab.tiers,t.tier_label)}</span><small>{describeBand(t,standard)}</small></li>)}</ul>:"—"}</dd></dl></div>
    </aside>
  </div>;
}
function EvidenceCard({assessment}:{assessment:PeriodKpiAssessment}){const [records,setRecords]=useState<AssessmentEvidence[]>([]),[busy,setBusy]=useState(false);const load=useCallback(()=>api.getAssessmentEvidence(assessment.id).then(result=>setRecords(result.evidence)),[assessment.id]);useEffect(()=>{void load()},[load]);async function upload(file:File){setBusy(true);try{const target=await api.getAssessmentEvidenceUploadUrl(assessment.id,file.name);const uploaded=await fetch(target.upload_url,{method:"PUT",headers:{"x-ms-blob-type":"BlockBlob","content-type":file.type||"application/octet-stream"},body:file});if(!uploaded.ok)throw new Error("Evidence upload failed");const digest=await crypto.subtle.digest("SHA-256",await file.arrayBuffer());const hash=Array.from(new Uint8Array(digest),byte=>byte.toString(16).padStart(2,"0")).join("");await api.createAssessmentEvidence({assessment_id:assessment.id,blob_path:target.blob_path,content_type:file.type||"application/octet-stream",file_size_bytes:file.size,content_sha256:hash,visibility:"contractor",caption:file.name,supersedes_id:records[0]?.id});await load()}finally{setBusy(false)}}return <div className="assessment-rail-card assessment-evidence-card"><div className="assessment-rail-head"><h4>Evidence</h4><label className="btn-sm">{busy?"Uploading…":"Add version"}<input type="file" hidden disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file)void upload(file)}}/></label></div><p>Immutable and content-hashed. The newest version supersedes the last.</p>{records.length?<ul className="assessment-evidence">{records.map((record,index)=><li key={record.id}>{fileIcon}<span className="grow">{record.caption??"Evidence"}<small>{record.visibility==="contractor"?"Contractor-visible":"Internal"} · {formatDate(record.uploaded_at)} · {record.uploaded_by}{index>0?" · superseded":""}</small></span><code className="mono-ref">{record.content_sha256.slice(0,8)}…</code></li>)}</ul>:<p>No evidence versions are attached.</p>}</div>}
// Which observation an occurrence came from, in words a reviewer can act on.
// The source_ref is a machine key the poll and the intake both build; showing
// it raw ("FixedRouteDepartures:avail_pullout:20260904|1305|2") tells a reader
// nothing about which module to open or what to search for there.
export function occurrenceSourceLabel(sourceRef: string | null | undefined): { module: string; reference: string; to: string } | null {
  if (!sourceRef) return null;
  const [table, rest] = [sourceRef.slice(0, sourceRef.indexOf(":")), sourceRef.slice(sourceRef.indexOf(":") + 1)];
  const tail = rest.slice(rest.indexOf(":") + 1);
  if (table === "MonitoredMissedTrips") {
    const [trip, date] = tail.split("|");
    return { module: "Missed Trips", reference: `Trip ${trip}${date ? ` · ${formatDate(date)}` : ""}`, to: "/compliance" };
  }
  if (table === "FixedRouteDepartures") {
    const [date, block, run] = tail.split("|");
    return { module: "Garage Departures · Fixed Route", reference: `Block ${block}/${run}${date ? ` · ${formatDate(date)}` : ""}`, to: "/compliance" };
  }
  if (table === "OnDemandDepartures") return { module: "Garage Departures · On-Demand", reference: `Duty ${tail}`, to: "/compliance" };
  return { module: table, reference: tail, to: "/compliance" };
}

function Occurrences({rows,periodSelected,busy,claims,onReview,onAmount,onRelief}:{rows:ComplianceOccurrence[];periodSelected:boolean;busy:boolean;claims:ExcusableDelayClaim[];onReview:(o:ComplianceOccurrence,s:"candidate"|"confirmed"|"dismissed",a:"contractor_error"|"excusable"|"mvta_directed"|"undetermined",reason?:string)=>void;onAmount:(o:ComplianceOccurrence,amount:number,note:string)=>void;onRelief:(o:ComplianceOccurrence,reliefId:string|null)=>void}){const {prompt}=useAppDialog();const dismiss=async(o:ComplianceOccurrence)=>{const reason=await prompt({title:"Dismiss occurrence",label:"Dismissal reason",confirmLabel:"Dismiss occurrence",multiline:true,required:true});if(reason)onReview(o,"dismissed","undetermined",reason)};
// Some penalties are a range, not a number - damage reimbursement runs
// $2,500-$10,000 - so the contract sets the bounds and a reviewer sets the
// figure on the facts. Recorded with a reason, because it is a judgement, and
// the month is not complete while any confirmed occurrence still wants one.
const setAmount=async(o:ComplianceOccurrence)=>{const raw=await prompt({title:`Penalty amount for ${o.standard_name}`,description:`The contract sets this between ${money(o.penalty_amount_min??0)} and ${money(o.penalty_amount_max??0)}. Enter the amount and what it rests on.`,label:"Amount and reason, e.g. 4200 — body shop estimate 2026-088",confirmLabel:"Record amount",required:true});if(!raw)return;const match=/^\s*\$?([0-9]+(?:\.[0-9]{1,2})?)\s*[—:-]?\s*(.*)$/.exec(raw);if(!match||!match[2].trim())return;onAmount(o,Number(match[1]),match[2].trim())};
const ranged=(o:ComplianceOccurrence)=>o.penalty_amount_min!==null&&o.penalty_amount_min!==undefined&&o.penalty_amount_max!==null&&o.penalty_amount_max!==undefined;
const awaiting=rows.filter(o=>o.review_status==="confirmed"&&ranged(o)&&(o.assessed_amount===null||o.assessed_amount===undefined));
return <section><div className="assessment-section-head"><div><h3>Occurrence Log</h3><p>{periodSelected?"Showing the selected Assessment Period.":"Showing recent occurrences for the Agreement contractor."}</p></div>{awaiting.length>0&&<span className="assessment-status stale">{awaiting.length} awaiting an amount</span>}</div>{awaiting.length>0&&<div className="assessment-warning">{awaiting.length} confirmed {awaiting.length===1?"occurrence carries":"occurrences carry"} a penalty the contract states as a range. The month cannot be read as complete until a reviewer records each figure.</div>}{!rows.length?<Empty>No occurrences are currently recorded.</Empty>:<div className="assessment-table-wrap"><table className="data"><thead><tr><th>Date</th><th>Contractor / KPI</th><th>Description</th><th>Observed in</th><th>Status</th><th>Attribution</th><th>Relief</th><th>Amount</th><th>Review</th></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td>{formatDate(o.service_date)}</td><td>{o.contractor_name}<small>{o.standard_name}</small></td><td>{o.description}</td><td>{(()=>{const source=occurrenceSourceLabel(o.source_ref);return source?<><Link to={source.to}>{source.module}</Link><small className="mono-ref">{source.reference}</small></>:<small>Entered by hand</small>})()}</td><td>{o.review_status}</td><td>{o.attribution}</td><td>{o.review_status==="confirmed"?<select aria-label="Excusable-delay claim" disabled={busy||!claims.length} value={o.relief_id??""} onChange={e=>onRelief(o,e.target.value||null)}><option value="">{claims.length?"No claim":"No approved claims"}</option>{claims.map(c=><option key={c.id} value={c.id}>{c.event_description}</option>)}</select>:<small>—</small>}</td><td>{ranged(o)?(o.assessed_amount===null||o.assessed_amount===undefined?<button disabled={busy} onClick={()=>void setAmount(o)}>Set amount…</button>:<><strong>{money(o.assessed_amount)}</strong><small>{o.assessed_by}</small></>):<small>—</small>}</td><td><button disabled={busy||o.review_status==="confirmed"} onClick={()=>onReview(o,"confirmed","contractor_error")}>Confirm</button><button disabled={busy||o.review_status==="dismissed"} onClick={()=>void dismiss(o)}>Dismiss</button></td></tr>)}</tbody></table></div>}</section>}
// The month's hand-entered figures as a checklist: one line per standard the
// month scores by a typed figure, missing ones first, each entered in place.
// The period's rows say which standards those are; before the first compute
// the catalog's scored flag stands in.
function Metrics({checklist:list,computed,period,busy,onCatalog,onSave}:{checklist:MetricsChecklist;computed:boolean;period:AssessmentPeriod|undefined;busy:boolean;onCatalog:()=>void;onSave:(id:string,value:number,note:string)=>void}){
  if(!period)return <Empty>Open this Assessment Period to enter its figures.</Empty>;
  const canEnter=!["finalized","issued"].includes(period.status);
  return <section className="assessment-stack">
    <div className="assessment-section-head"><div><h3>Monthly metrics</h3><p>The figures nobody feeds automatically: what the month's value was, and where it was read from. The month cannot compute as complete until every scored figure is in.</p></div>{list.scored.length>0&&<div className="assessment-section-actions"><span className="muted" style={{fontSize:12}}>{list.entered} of {list.scored.length} entered</span><span className="assessment-progress" aria-hidden="true"><i style={{width:`${Math.round(100*list.entered/list.scored.length)}%`}}/></span></div>}</div>
    {list.scored.length?<div className="assessment-table-wrap"><div className="assessment-metric-head"><span>Standard</span><span>{formatMonth(period.service_month)} value</span><span>Source of record</span><span>Owner · entered</span><span/></div>{list.scored.map(item=><MetricRow key={item.standard.id} item={item} busy={busy||!canEnter} onSave={onSave}/>)}</div>:<Empty>{computed?"Every figure this month scores arrives automatically.":"No hand-entered standard is scored."}</Empty>}
    {!canEnter&&<p className="muted" style={{margin:0,fontSize:12}}>A {period.status} month keeps the figures it was scored with.</p>}
    {canEnter&&list.scored.length>0&&<p className="muted" style={{margin:0,fontSize:12}}>A saved figure stamps who entered it and when. Changing one marks the month stale until it is recomputed.</p>}
    {list.unscored.length>0&&<><p className="assessment-group-label">Not scored this month</p><div className="assessment-glance-meta" style={{margin:0}}>{list.unscored.map(standard=><span key={standard.id}>{standard.name}</span>)}<button type="button" className="assessment-link-button" onClick={onCatalog}>Change assignments in Standards</button></div></>}
  </section>;
}
function MetricRow({item,busy,onSave}:{item:{standard:ContractorPerformanceStandard;entry:ManualMetricEntry|undefined};busy:boolean;onSave:(id:string,value:number,note:string)=>void}){
  const {standard,entry}=item;
  const [editing,setEditing]=useState(!entry),[value,setValue]=useState(entry?String(entry.metric_value):""),[note,setNote]=useState(entry?.source_note??"");
  // Reset only when the saved entry itself changes, not on every reload that
  // hands back the same one - an edit in progress survives the refresh.
  useEffect(()=>{setEditing(!entry);setValue(entry?String(entry.metric_value):"");setNote(entry?.source_note??"")},[entry?.id,entry?.entered_at]); // eslint-disable-line react-hooks/exhaustive-deps
  const unit=standard.unit_label==="percent"?"%":standard.unit_label;
  return <div className="assessment-metric-row">
    <div><strong>{standard.name}</strong><small>{standard.code} · {standard.unit_label}</small></div>
    {editing?<label className="assessment-measure"><input type="number" aria-label={`${standard.name} value`} placeholder="Value" value={value} disabled={busy} onChange={e=>setValue(e.target.value)}/><span>{unit}</span></label>:<div><strong>{entry?.metric_value.toLocaleString("en-US")}</strong> <span className="muted">{unit}</span></div>}
    {editing?<input className="assessment-metric-input" aria-label={`${standard.name} source of record`} placeholder="Source of record" value={note} disabled={busy} onChange={e=>setNote(e.target.value)}/>:<div>{entry?.source_note}</div>}
    <div className="muted" style={{fontSize:12}}>{entry?`${entry.entered_by} · ${formatDate(entry.entered_at)}`:standard.assigned_to||"No owner set"}</div>
    <div className="assessment-metric-state">{entry?<span className="pill-sm pill-success">Entered</span>:<span className="pill-sm pill-warning">Missing</span>}{editing?<button type="button" className="btn-sm" disabled={busy||value===""||!note.trim()} onClick={()=>onSave(standard.id,Number(value),note.trim())}>Save</button>:<button type="button" className="btn-sm" disabled={busy} onClick={()=>setEditing(true)}>Change</button>}</div>
  </div>;
}
function ManagerReview({period,rows,totals,busy,onReview,onCompute,onFinalize}:{period:AssessmentPeriod|undefined;rows:PeriodKpiAssessment[];totals:AssessmentTotals;busy:boolean;onReview:(r:PeriodKpiAssessment,a:"confirmed"|"adjusted"|"waived",amount?:number,reason?:string)=>void;onCompute:()=>void;onFinalize:()=>void}){const {prompt}=useAppDialog();const adjust=(r:PeriodKpiAssessment)=>recommendAdjustment(prompt,r,onReview),waive=(r:PeriodKpiAssessment)=>recommendWaiver(prompt,r,onReview);if(!period)return <Empty>Select an Assessment Period to begin review.</Empty>;return <section><div className="assessment-section-head"><div><h3>Assessment Review</h3><p>Automation calculates a Proposed Penalty; a reviewer recommends treatment before a separate Issuing Authority finalizes it.</p></div><div><button disabled={busy||!["open","stale","reopened"].includes(period.status)} onClick={onCompute}>{period.status==="stale"?"Recompute":"Compute"}</button> <button disabled={busy||period.status!=="in_validation"||totals.pending>0} onClick={onFinalize}>Finalize {money(totals.final)}</button></div></div>{!rows.length?<Empty>Compute the period to create its review queue.</Empty>:rows.map(r=><div className="assessment-review-row" key={r.id}><div><strong>{r.name}</strong><small>{r.metric_display} · proposed {money(r.proposed_amount)}</small></div><span>{(()=>{const d=reviewDisplay(period.status,r);return `${d.heading}: ${d.value}`})()}</span><button disabled={busy||period.status!=="in_review"} onClick={()=>onReview(r,"confirmed")}>Recommend confirmation</button><button disabled={busy||period.status!=="in_review"} onClick={()=>void adjust(r)}>Recommend adjustment</button><button disabled={busy||period.status!=="in_review"} onClick={()=>void waive(r)}>Recommend waiver</button></div>)}</section>}
function Disputes({period,rows}:{period:AssessmentPeriod|undefined;rows:PeriodKpiAssessment[]}){const [records,setRecords]=useState<AssessmentDispute[]>([]);useEffect(()=>{if(!period){setRecords([]);return}void api.getAssessmentDisputes(period.id).then(result=>setRecords(result.disputes))},[period]);if(!period)return null;return <section className="assessment-stack" style={{gap:10}}><div className="assessment-section-head"><div><h4 style={{margin:0}}>Disputes</h4><p>A dispute names the items it challenges; unchallenged items stay final.</p></div></div>{records.length?<div className="assessment-table-wrap"><table className="data"><thead><tr><th>Against</th><th>Items</th><th>Basis</th><th>Filed</th><th>Status</th></tr></thead><tbody>{records.map(dispute=><tr key={dispute.id}><td>Final Assessment v{dispute.report_version}</td><td>{dispute.item_count}</td><td>{dispute.basis}</td><td>{formatDate(dispute.submitted_at)}</td><td><span className={`pill-sm ${dispute.outcome?"pill-accent":"pill-warning"}`}>{dispute.outcome??dispute.status}</span></td></tr>)}</tbody></table></div>:<Empty>{period.status==="issued"&&rows.length?"No disputes have been filed against this Final Assessment.":"Disputes become available once the Final Assessment is issued."}</Empty>}</section>}
// Read-only mirror of the catalog. Editing lives in Administration >
// Performance Standards: changing a band is contract governance, and every
// role that can open this module can read a scorecard but must not be able to
// change what produced it.
function bandText(standard:ContractorPerformanceStandard,tier:ContractorStandardTier){const ratio=standard.unit_label==="percent"||standard.unit_label==="%";const show=(value:number|null)=>value===null?"":String(ratio?Number((value*100).toFixed(4)):value);const low=show(tier.bound_low),high=show(tier.bound_high);const band=low||high?` ${low||"–"}…${high||"–"}`:"";const charge=tier.penalty_basis==="none"?"no penalty":`${money(Number(tier.penalty_amount))} ${tier.penalty_basis.replaceAll("_"," ")}`;return `${tier.tier_label}${band}: ${charge}${tier.triggers_cap?" · CAP":""}`}
function Standards({standards,tiers}:{standards:ContractorPerformanceStandard[];tiers:ContractorStandardTier[]}){const isAdmin=useAuth().roles.includes("OCC.Admin");return <section><div className="assessment-section-head"><div><h3>Standards</h3><p>The performance standards catalog and the tier bands that govern scoring. {isAdmin?<>Edit these under <Link to="/admin/performance-standards">Administration › Performance Standards</Link>.</>:"Changing a band or an Agreement assignment requires Administrator access."}</p></div><span>{standards.length} standards · {tiers.length} tiers</span></div><div className="assessment-table-wrap"><table className="data"><thead><tr><th>Code / standard</th><th>Type</th><th>Priority</th><th>Scored</th><th>Source</th><th>Owner</th><th>Tier bands</th></tr></thead><tbody>{standards.map(s=><tr key={s.id}><td><strong>{s.code}</strong><small>{s.name}</small></td><td>{s.standard_type}</td><td>{s.priority}</td><td>{s.is_scored?"Yes":"No"}</td><td>{sourceLabel(s.measurement_source,s.source_system)}{isAutomated(s.measurement_source)&&!s.resolver_key?<small> · no resolver</small>:null}</td><td>{s.assigned_to??"—"}<small>{s.responsible_team??""}</small></td><td>{tiers.filter(t=>t.standard_id===s.id&&!t.agreement_id&&!t.effective_end_date).sort((a,b)=>a.tier_order-b.tier_order).map(t=>bandText(s,t)).join(" · ")||"—"}</td></tr>)}</tbody></table></div></section>}

function ContractorSetup({contractors,canEdit,busy,onSave}:{contractors:ContractorRecord[];canEdit:boolean;busy:boolean;onSave:(id:string,input:{name:string;contract_start_date:string;contract_end_date:string|null;is_active:boolean})=>void}){
  const [selected,setSelected]=useState("new"),[name,setName]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[active,setActive]=useState(true);
  useEffect(()=>{const c=contractors.find(x=>x.id===selected);setName(c?.name??"");setStart(inputDate(c?.contract_start_date));setEnd(inputDate(c?.contract_end_date));setActive(c?.is_active??true)},[selected,contractors]);
  return <section className="contractor-setup"><div className="assessment-section-head"><div><span className="assessment-eyebrow">Administration</span><h3>Agreement contractor</h3><p>Maintain the sole Assessment Contractor for this Agreement.</p></div></div>{!canEdit&&<div className="assessment-warning">Administrator access is required to change the Agreement contractor.</div>}<div className="contractor-form"><label><span>Contractor record</span><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="new">Add the Agreement contractor</option>{contractors.map(c=><option key={c.id} value={c.id}>{c.name}{c.is_active?"":" (inactive)"}</option>)}</select></label><label><span>Contractor name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Legal or operating name" disabled={!canEdit}/></label><label><span>Agreement start date</span><input type="date" value={start} onChange={e=>setStart(e.target.value)} disabled={!canEdit}/><small>{start?formatDate(start):"MM/DD/YYYY"}</small></label><label><span>Agreement end date</span><input type="date" value={end} onChange={e=>setEnd(e.target.value)} disabled={!canEdit}/><small>{end?formatDate(end):"Optional · MM/DD/YYYY"}</small></label><label className="contractor-active"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)} disabled={!canEdit}/><span>Current Agreement contractor</span></label><button className="btn-primary" disabled={!canEdit||busy||!name.trim()||!start} onClick={()=>onSave(selected==="new"?crypto.randomUUID():selected,{name:name.trim(),contract_start_date:start.replace(/-/g,""),contract_end_date:end?end.replace(/-/g,""):null,is_active:active})}>{selected==="new"?"Add contractor":"Save contractor"}</button></div>{contractors.length>0&&<div className="contractor-list">{contractors.map(c=><div key={c.id}><div><strong>{c.name}</strong><span>{c.is_active?"Current":"Historical"}</span></div><p>{formatDate(c.contract_start_date)} – {c.contract_end_date?formatDate(c.contract_end_date):"Ongoing"}</p></div>)}</div>}</section>
}
