import { useEffect, useState } from "react";
import type { AssessmentPeriod, AssessmentReport } from "@mvta/shared";
import { api } from "../../../config.js";
import { useAppDialog } from "../../../components/AppDialog.js";
import { Empty, formatDate } from "./assessmentFormat.js";

// Report Version counts renders, not issuances: a voided proof keeps its number.
function artifactLabel(report:AssessmentReport):string{if(report.issuance_type==="preliminary")return "Validation Draft";if(report.issued_at)return "Final Assessment";return report.voided_at?"Issuance Proof (voided)":"Issuance Proof"}
export function ReportWorkflow({period,busy,act}:{period:AssessmentPeriod|undefined;busy:boolean;act:(action:()=>Promise<unknown>)=>Promise<void>}){
  const {prompt}=useAppDialog();
  const [reports,setReports]=useState<AssessmentReport[]>([]);
  // The exact archived bytes, opened here before anyone attests to sharing
  // or issues. The api fetches them with the caller's token; an iframe
  // cannot, so the HTML goes in as srcDoc, sandboxed so it can run nothing.
  const [preview,setPreview]=useState<{id:string;html:string}|null>(null);
  useEffect(()=>{if(!period){setReports([]);setPreview(null);return}let active=true;api.getAssessmentReports(period.id).then(result=>{if(active)setReports(result.reports)});return()=>{active=false}},[period]);
  const open=async(report:AssessmentReport)=>{const html=await api.getAssessmentReportHtml(report.id);setPreview({id:report.id,html})};
  const download=async(report:AssessmentReport)=>{const html=await api.getAssessmentReportHtml(report.id);const url=URL.createObjectURL(new Blob([html],{type:"text/html"}));const a=document.createElement("a");a.href=url;a.download=`assessment-${report.period_id}-${report.issuance_type}-v${report.version}.html`;a.click();URL.revokeObjectURL(url)};
  if(!period)return <Empty>Select an Assessment Period to work with its official artifacts.</Empty>;
  const draft=reports.find(report=>report.issuance_type==="preliminary"&&!report.issued_at)!,proof=reports.find(report=>report.issuance_type==="final"&&!report.issued_at&&!report.voided_at)!;
  // A period that corrects an issued month must say why on the proof's cover;
  // the server refuses a reason on any other period, so ask only then.
  const prepareProof=async()=>{let reason:string|null=null;if(period.supersedes_period_id){reason=await prompt({title:"Prepare Issuance Proof",label:"Why this Final Assessment supersedes the issued one",confirmLabel:"Prepare proof",multiline:true,required:true});if(!reason)return}void reload(()=>api.createAssessmentReport(period.id,"final",reason??undefined))};
  const reload=async(action:()=>Promise<unknown>)=>{await act(action);const result=await api.getAssessmentReports(period.id);setReports(result.reports)};
  const recordSharing=async()=>{if(!draft)return;const recipient=await prompt({title:"Record draft sharing",label:"Validation Draft recipient",confirmLabel:"Continue",required:true});const attestation=await prompt({title:"Record sender attestation",label:"Sender attestation",confirmLabel:"Record sharing",multiline:true,required:true});if(recipient&&attestation)void reload(()=>api.shareValidationDraft(period.id,draft.id,recipient,attestation))};
  const issueFinal=async()=>{if(!proof)return;const recipient=await prompt({title:"Issue Final Assessment",label:"Final Assessment recipient",confirmLabel:"Continue",required:true});const attestation=await prompt({title:"Record sender attestation",label:"Sender attestation",confirmLabel:"Issue Final Assessment",multiline:true,required:true});if(recipient&&attestation)void reload(()=>api.issueAssessmentReport(proof.id,recipient,attestation))};
  return <section><div className="assessment-section-head"><div><h3>Official Assessment Package</h3><p>Generate a Validation Draft, record sharing, prepare the Issuance Proof, then issue the immutable Final Assessment. Preparing another proof voids the last; only issuing creates a Final Assessment.</p></div></div><div className="assessment-card"><button disabled={busy||period.status!=="in_review"} onClick={()=>void reload(()=>api.createAssessmentReport(period.id,"preliminary"))}>Generate Validation Draft</button> <button disabled={busy||!draft||period.status!=="in_review"} onClick={()=>void recordSharing()}>Record draft sharing</button> <button disabled={busy||period.status!=="finalized"} onClick={()=>void prepareProof()}>{proof?"Prepare a new Issuance Proof":"Prepare Issuance Proof"}</button> <button disabled={busy||!proof||period.status!=="finalized"} onClick={()=>void issueFinal()}>Issue Final Assessment</button></div>{reports.length?<div className="assessment-table-wrap"><table className="data"><thead><tr><th>Artifact</th><th>Version</th><th>Issued</th><th>Hash</th><th>Open</th></tr></thead><tbody>{reports.map(report=><tr key={report.id} className={report.voided_at?"assessment-voided":undefined}><td>{artifactLabel(report)}{report.supersede_reason?<div className="muted">Supersedes: {report.supersede_reason}</div>:null}</td><td>{report.version}</td><td>{formatDate(report.issued_at)}</td><td><code>{report.content_sha256.slice(0,12)}…</code>{report.proof_sha256?<div className="muted">proof <code>{report.proof_sha256.slice(0,12)}…</code></div>:null}</td><td><button disabled={busy} onClick={()=>void open(report)}>Preview</button> <button disabled={busy} onClick={()=>void download(report)}>Download official HTML</button></td></tr>)}</tbody></table></div>:<Empty>No assessment artifacts have been generated.</Empty>}{preview&&<div className="assessment-preview"><div className="assessment-section-head"><h4>Archived bytes of {artifactLabel(reports.find(r=>r.id===preview.id)!)} · SHA-256 <code>{reports.find(r=>r.id===preview.id)?.content_sha256.slice(0,16)}…</code></h4><button onClick={()=>setPreview(null)}>Close</button></div><iframe title="Assessment artifact preview" sandbox="" srcDoc={preview.html}/></div>}</section>;
}
