export interface ReportAssessment { name:string;standardType:string;metricDisplay:string;targetDisplay:string;tierLabel:string;occurrenceCount:number;baseAmount:number;reliefAmount:number;rampUpMultiplier:number;escalationMultiplier:number;assessedAmount:number;managerAction:string;managerReason:string|null;dataCompletenessPct:number|null }
export interface AssessmentReportModel { reportId:string;issuanceType:"preliminary"|"final";version:number;contractorName:string;serviceMonth:string;rampUpStage:string;issuedAt:string|null;issuedBy:string|null;disputeDeadline:string|null;assessedTotal:number;assessments:ReportAssessment[] }
export function escapeHtml(value:unknown):string{return String(value??"").replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]!);}
const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(value);
export function renderAssessmentReport(model:AssessmentReportModel):string{
 const watermark=model.issuanceType==="preliminary"?'<div class="watermark">PRELIMINARY — FOR CONTRACTOR REVIEW — NOT AN ASSESSMENT</div>':"";
 const rows=model.assessments.map(a=>`<tr><td>${escapeHtml(a.name)}</td><td>${escapeHtml(a.metricDisplay)}</td><td>${escapeHtml(a.targetDisplay)}</td><td>${escapeHtml(a.tierLabel)}</td><td>${money(a.assessedAmount)}</td></tr>`).join("");
 const details=model.assessments.map(a=>`<section class="kpi"><h3>${escapeHtml(a.name)}</h3><p><b>Computation:</b> ${money(a.baseAmount)} − ${money(a.reliefAmount)} × ${a.rampUpMultiplier} × ${a.escalationMultiplier} = <b>${money(a.assessedAmount)}</b></p><p><b>Manager action:</b> ${escapeHtml(a.managerAction)}${a.managerReason?` — ${escapeHtml(a.managerReason)}`:""}</p><p><b>Data completeness:</b> ${a.dataCompletenessPct===null?"Not reported":`${a.dataCompletenessPct}%`}</p></section>`).join("");
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>MVTA Contractor Performance Assessment</title><style>body{font-family:Arial,sans-serif;color:#172033;margin:0;font-size:10pt}header{border-bottom:4px solid #005ea8;padding-bottom:14px}h1{font-size:24pt;margin:0 0 8px}h2{color:#005ea8;margin-top:24px}table{width:100%;border-collapse:collapse}th,td{padding:7px;border-bottom:1px solid #ccd5df;text-align:left}th{background:#eaf2f8}.meta{display:grid;grid-template-columns:1fr 1fr;gap:5px}.watermark{padding:12px;background:#fff3cd;color:#7a4d00;font-weight:bold;text-align:center;margin-bottom:16px}.kpi{break-inside:avoid;border:1px solid #ccd5df;padding:10px;margin:10px 0}.footer{margin-top:28px;font-size:8pt;color:#566} @page{size:letter portrait;margin:.6in}@media print{thead{display:table-header-group}.footer:after{content:" — Convenience PDF; official record is the archived HTML identified on the cover"}}</style></head><body>${watermark}<header><h1>Contractor Performance Assessment</h1><div class="meta"><span><b>Contractor:</b> ${escapeHtml(model.contractorName)}</span><span><b>Service month:</b> ${escapeHtml(model.serviceMonth)}</span><span><b>Report:</b> ${escapeHtml(model.reportId)} v${model.version}</span><span><b>Status:</b> ${escapeHtml(model.issuanceType)}</span><span><b>Ramp-up:</b> ${escapeHtml(model.rampUpStage)}</span><span><b>Issued:</b> ${escapeHtml(model.issuedAt??"Not issued")}</span></div></header><h2>Summary</h2><p><b>Total assessed: ${money(model.assessedTotal)}</b></p><h2>KPI Results</h2><table><thead><tr><th>KPI</th><th>Metric</th><th>Target</th><th>Tier</th><th>Amount</th></tr></thead><tbody>${rows}</tbody></table><h2>Computation detail</h2>${details}<h2>Dispute rights</h2><p>${model.issuanceType==="final"?`Written notice is due by <b>${escapeHtml(model.disputeDeadline)}</b>. Identify the penalty, state the basis, attach supporting documentation, and reference any outage, malfunction, or excusable-delay event.`:"No dispute clock begins from this preliminary report."}</p><div class="footer">Official record: ${escapeHtml(model.reportId)}</div></body></html>`;
}
