export interface ReportAssessment { name:string;standardType:string;metricDisplay:string;/** "412,300 miles ÷ 31 road calls": how a figure made from parts was made. */metricWorking?:string|null;targetDisplay:string;tierLabel:string;occurrenceCount:number;baseAmount:number;escalationMultiplier:number;computedAmount:number;excludedOccurrenceCount:number;excludedUnitQuantity:number;reviewAction:string;reviewReason:string|null;assessedAmount:number;dataCompletenessPct:number|null }
export interface ReportOccurrence { standardName:string;serviceDate:string;description:string;quantity:number;qualifierCode:string|null;sourceRef:string|null;evidenceHashes?:string[];counted:boolean;exclusionReason:string|null }
export interface ReportException { standardName:string;reason:string;missingDataOwner:string;remediationAction:string;expectedCorrectionDate:string }
export interface ReportCap { standardName:string;triggerReason:string;dueAt:string|null;status:string }
export interface ReportOtpExclusion { reasonCode:string;stopCount:number }
export interface ReportDataSource { standardName:string;source:string;handEntered:boolean;dataCompletenessPct:number|null;notAssessable?:boolean }
export interface AssessmentReportModel { reportId:string;issuanceType:"preliminary"|"final";version:number;contractorName:string;serviceMonth:string;issuedAt:string|null;issuedBy:string|null;disputeDeadline:string|null;isPartial:boolean;assessedTotal:number;assessments:ReportAssessment[];evidence?:{assessmentName:string;caption:string;contentSha256:string}[];occurrences?:ReportOccurrence[];exceptions?:ReportException[];caps?:ReportCap[];dataSources?:ReportDataSource[];otpExclusions?:ReportOtpExclusion[] }
const escapeHtml=(value:unknown)=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]!);
const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(value);
// Dates arrive as ISO strings or the schema's CHAR(8) service dates; both print MM/DD/YYYY.
const isoDay=(value:string)=>/^\d{8}$/.test(value)?`${value.slice(0,4)}-${value.slice(4,6)}-${value.slice(6,8)}`:value.slice(0,10);
const displayDate=(value:string|null)=>value?new Intl.DateTimeFormat("en-US",{month:"2-digit",day:"2-digit",year:"numeric",timeZone:"America/Chicago"}).format(new Date(`${isoDay(value)}T12:00:00Z`)):"Not issued";
const displayMonth=(value:string)=>{const digits=value.replace(/\D/g,"");if(digits.length!==6)return value;return new Intl.DateTimeFormat("en-US",{month:"long",year:"numeric",timeZone:"America/Chicago"}).format(new Date(Date.UTC(Number(digits.slice(0,4)),Number(digits.slice(4,6))-1,1,12)));};

export function renderAssessmentReport(model:AssessmentReportModel):string{
  const validation=model.issuanceType==="preliminary";
  const watermark=validation?'<div class="watermark">VALIDATION DRAFT — NON-BINDING</div>':"";
  const rows=model.assessments.map(a=>`<tr><td>${escapeHtml(a.name)}</td><td>${escapeHtml(a.metricDisplay)}${a.metricWorking?`<br><small>${escapeHtml(a.metricWorking)}</small>`:""}</td><td>${escapeHtml(a.targetDisplay)}</td><td>${escapeHtml(a.tierLabel)}</td><td>${money(a.assessedAmount)}</td></tr>`).join("");
  const details=model.assessments.map(a=>`<section class="kpi"><h3>${escapeHtml(a.name)}</h3>${a.metricWorking?`<p><b>Figure:</b> ${escapeHtml(a.metricDisplay)}, from ${escapeHtml(a.metricWorking)}</p>`:""}<p><b>Computed:</b> ${money(a.baseAmount)} × ${a.escalationMultiplier} = ${money(a.computedAmount)}${a.excludedOccurrenceCount||a.excludedUnitQuantity?` <i>(after excluding ${a.excludedOccurrenceCount} occurrence${a.excludedOccurrenceCount===1?"":"s"}${a.excludedUnitQuantity?`, ${a.excludedUnitQuantity} units`:""} from the inputs)</i>`:""}</p><p><b>${validation?"Recommendation":"Binding decision"}:</b> ${escapeHtml(a.reviewAction)}${a.reviewReason?` — ${escapeHtml(a.reviewReason)}`:""}</p><p><b>${validation?"Recommended amount":"Binding amount"}:</b> <b>${money(a.assessedAmount)}</b></p><p><b>Data completeness:</b> ${a.dataCompletenessPct===null?"Not Assessable":`${a.dataCompletenessPct}%`}</p></section>`).join("");
  const evidence=(model.evidence??[]).map(item=>`<li><b>${escapeHtml(item.assessmentName)}</b>: ${escapeHtml(item.caption)} — SHA-256 ${escapeHtml(item.contentSha256)}</li>`).join("");
  const occurrences=model.occurrences??[],exceptions=model.exceptions??[],caps=model.caps??[],sources=model.dataSources??[],otpExclusions=model.otpExclusions??[];
  const occurrenceRows=occurrences.map(o=>`<tr><td>${escapeHtml(o.standardName)}</td><td>${displayDate(o.serviceDate)}</td><td>${escapeHtml(o.description)}${o.qualifierCode?` <i>(${escapeHtml(o.qualifierCode)})</i>`:""}</td><td>${o.quantity}</td><td>${o.counted?"Counted":"Excluded"}</td><td><code>${escapeHtml(o.sourceRef??"")}</code>${(o.evidenceHashes??[]).map(h=>`<br><small>evidence ${escapeHtml(h.slice(0,16))}…</small>`).join("")}</td></tr>`).join("");
  const occurrenceSchedule=occurrences.length?`<table><thead><tr><th>Standard</th><th>Date</th><th>Description</th><th>Qty</th><th>Status</th><th>Reference</th></tr></thead><tbody>${occurrenceRows}</tbody></table>`:"<p>No occurrences were counted against this Assessment Period.</p>";
  // Grouped by cause, so what was removed in the contractor's favor reads as
  // policy applied rather than a list of dates.
  const byCause=new Map<string,typeof occurrences>();for(const o of occurrences){if(o.counted)continue;const key=o.exclusionReason??"Excluded";byCause.set(key,[...(byCause.get(key)??[]),o]);}
  const causeBlocks=[...byCause.entries()].map(([cause,items])=>`<h3>${escapeHtml(cause)}</h3><ul>${items.map(o=>`<li><b>${escapeHtml(o.standardName)}</b>, ${displayDate(o.serviceDate)}: ${escapeHtml(o.description)}</li>`).join("")}</ul>`).join("");
  const otpBlock=otpExclusions.length?`<h3>On-time performance stop exclusions</h3><ul>${otpExclusions.map(x=>`<li>${escapeHtml(x.reasonCode)}: ${x.stopCount} stop${x.stopCount===1?"":"s"} excluded</li>`).join("")}</ul>`:"";
  const exclusions=causeBlocks||otpBlock?causeBlocks+otpBlock:"<p>No exclusions or relief were applied.</p>";
  const capList=caps.length?`<table><thead><tr><th>Standard</th><th>Trigger</th><th>Submission due</th><th>Status</th></tr></thead><tbody>${caps.map(c=>`<tr><td>${escapeHtml(c.standardName)}</td><td>${escapeHtml(c.triggerReason)}</td><td>${c.dueAt?displayDate(c.dueAt):"Five business days from issuance"}</td><td>${escapeHtml(c.status)}</td></tr>`).join("")}</tbody></table><p>A Corrective Action Plan is due within five business days of issuance and must state root cause, corrective actions, responsible parties, timeline, monitoring plan, and closure criteria.</p>`:"<p>No Corrective Action Plan is required for this Assessment Period.</p>";
  const notes=model.assessments.filter(a=>a.reviewAction==="adjusted"||a.reviewAction==="waived");
  const managerNotes=notes.length?`<ul>${notes.map(a=>`<li><b>${escapeHtml(a.name)}</b>: ${validation?"recommended ":""}${escapeHtml(a.reviewAction)} to ${money(a.assessedAmount)} — ${escapeHtml(a.reviewReason??"no reason recorded")}</li>`).join("")}</ul>`:"<p>No adjustments or waivers were made.</p>";
  const exceptionList=exceptions.length?`<ul>${exceptions.map(e=>`<li><b>${escapeHtml(e.standardName)}</b> is Not Assessable: ${escapeHtml(e.reason)}. Owner ${escapeHtml(e.missingDataOwner)}; ${escapeHtml(e.remediationAction)}; expected by ${displayDate(e.expectedCorrectionDate)}.</li>`).join("")}</ul>`:"";
  const sourceRows=sources.map(d=>`<tr><td>${escapeHtml(d.standardName)}</td><td>${escapeHtml(d.source)}${d.handEntered?" <i>(hand-entered)</i>":""}</td><td>${d.notAssessable?"Not Assessable":d.dataCompletenessPct===null?"Not computed":`${d.dataCompletenessPct}%`}</td></tr>`).join("");
  const dataSources=sources.length?`<table><thead><tr><th>Standard</th><th>Source</th><th>Completeness</th></tr></thead><tbody>${sourceRows}</tbody></table>`:"<p>Data sources were not recorded for this artifact.</p>";
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>MVTA Contractor Performance Assessment</title><style>body{font-family:Arial,sans-serif;color:#172033;margin:0;font-size:10pt}header{border-bottom:4px solid #005ea8;padding-bottom:14px}h1{font-size:24pt;margin:0 0 8px}h2{color:#005ea8;margin-top:24px}table{width:100%;border-collapse:collapse}th,td{padding:7px;border-bottom:1px solid #ccd5df;text-align:left}th{background:#eaf2f8}.meta{display:grid;grid-template-columns:1fr 1fr;gap:5px}.watermark{padding:12px;background:#fff3cd;color:#7a4d00;font-weight:bold;text-align:center;margin-bottom:16px}.kpi{break-inside:avoid;border:1px solid #ccd5df;padding:10px;margin:10px 0}.footer{margin-top:28px;font-size:8pt;color:#566}@page{size:letter portrait;margin:.6in}@media print{thead{display:table-header-group}.footer:after{content:" — Convenience PDF; official record is the archived HTML identified on the cover"}}</style></head><body>${watermark}<header><h1>Contractor Performance Assessment</h1><div class="meta"><span><b>Contractor:</b> ${escapeHtml(model.contractorName)}</span><span><b>Assessment Period:</b> ${escapeHtml(displayMonth(model.serviceMonth))}</span><span><b>Artifact:</b> ${escapeHtml(model.reportId)} v${model.version}</span><span><b>Status:</b> ${validation?"Validation Draft":"Final Assessment"}</span><span><b>Issued:</b> ${displayDate(model.issuedAt)}</span></div></header><h2>Summary</h2><p><b>${model.isPartial?"Partial Assessed Total":"Assessed total"}: ${money(model.assessedTotal)}</b></p><h2>Performance standard results</h2><table><thead><tr><th>Standard</th><th>Metric</th><th>Target</th><th>Outcome</th><th>Amount</th></tr></thead><tbody>${rows}</tbody></table><h2>Computation detail</h2>${details}<h2>Occurrence schedule</h2>${occurrenceSchedule}<h2>Exclusions and relief applied</h2>${exclusions}<h2>Corrective Action Plans required</h2>${capList}<h2>Manager notes</h2>${managerNotes}<h2>Contractor Evidence</h2>${evidence?`<ul>${evidence}</ul>`:"<p>No Contractor Evidence was included.</p>"}<h2>Dispute rights</h2><p>${validation?"No contractual deadline begins from this Validation Draft.":`Written notice is due by <b>${displayDate(model.disputeDeadline)}</b>. Identify the Assessment Items challenged and attach supporting evidence.`}</p><h2>Data sources and completeness</h2>${exceptionList}${dataSources}<div class="footer">Official record: ${escapeHtml(model.reportId)}</div></body></html>`;
}
