import { app, type HttpRequest, type InvocationContext } from "@azure/functions";
import { addBusinessDays, assertHolidayCoverage } from "../lib/assessment/businessDays";
import { COMPLIANCE_MANAGER_ROLES, COMPLIANCE_READ_ROLES, COMPLIANCE_WRITE_ROLES, requireRole } from "../lib/auth";
import { getPool, sql } from "../lib/db";
import { isGuid } from "../lib/validation";

app.http("assessmentExceptionCreate", { route: "assessment-periods/{id}/exceptions", methods: ["POST"], authLevel: "anonymous", handler: async (request: HttpRequest, context: InvocationContext) => {
  const auth=requireRole(request,COMPLIANCE_MANAGER_ROLES);if(!auth.authorized)return{status:auth.status,jsonBody:{error:auth.message}};
  if(!isGuid(request.params.id))return{status:400,jsonBody:{error:"Invalid period id"}};
  let body:Record<string,unknown>;try{body=await request.json() as Record<string,unknown>;}catch{return{status:400,jsonBody:{error:"Request body must be valid JSON"}};}
  if(!isGuid(body.assessment_id)||![body.reason,body.missing_data_owner,body.remediation_action,body.expected_correction_date].every(value=>typeof value==="string"&&value.trim()))return{status:400,jsonBody:{error:"assessment_id, reason, missing_data_owner, remediation_action, and expected_correction_date are required"}};
  try{const pool=await getPool();const req=pool.request();req.input("period",sql.UniqueIdentifier,request.params.id);req.input("assessment",sql.UniqueIdentifier,body.assessment_id);req.input("reason",sql.NVarChar(1000),body.reason);req.input("owner",sql.NVarChar(200),body.missing_data_owner);req.input("action",sql.NVarChar(1000),body.remediation_action);req.input("date",sql.Date,body.expected_correction_date);req.input("actor",sql.NVarChar(200),auth.principal.userDetails??"onboard-console");const result=await req.query<{id:string}>(`IF EXISTS(SELECT 1 FROM PeriodKpiAssessments WHERE id=@assessment AND period_id=@period AND assessment_outcome='not_assessable') BEGIN DECLARE @id UNIQUEIDENTIFIER=NEWID();INSERT AssessmentExceptions(id,period_id,assessment_id,reason,missing_data_owner,remediation_action,expected_correction_date,authorized_by) VALUES(@id,@period,@assessment,@reason,@owner,@action,@date,@actor);INSERT ComplianceAssessmentAudit(entity_type,entity_id,action,actor,note) VALUES('assessment',@assessment,'exception_authorized',@actor,@reason);SELECT @id id;END`);if(!result.recordset[0])return{status:409,jsonBody:{error:"Only a Not Assessable item in this period can receive an exception"}};return{status:201,jsonBody:result.recordset[0]};}catch(error){context.error("POST assessment exception failed",error);return{status:500,jsonBody:{error:"Internal server error"}};}
}});

app.http("assessmentValidationShare", { route: "assessment-periods/{id}/validation-share", methods: ["POST"], authLevel: "anonymous", handler: async (request: HttpRequest, context: InvocationContext) => {
  const auth=requireRole(request,COMPLIANCE_WRITE_ROLES);if(!auth.authorized)return{status:auth.status,jsonBody:{error:auth.message}};
  if(!isGuid(request.params.id))return{status:400,jsonBody:{error:"Invalid period id"}};
  let body:Record<string,unknown>;try{body=await request.json() as Record<string,unknown>;}catch{return{status:400,jsonBody:{error:"Request body must be valid JSON"}};}
  if(!isGuid(body.report_id)||![body.recipient,body.delivery_method,body.sender_attestation].every(value=>typeof value==="string"&&value.trim()))return{status:400,jsonBody:{error:"report_id, recipient, delivery_method, and sender_attestation are required"}};
  try{const pool=await getPool();const now=new Date();const calendar=await pool.request().query<{holiday_date:Date}>(`SELECT holiday_date FROM MvtaHolidays`);const coverage=await pool.request().query<{coverage_through:Date}>(`SELECT coverage_through FROM MvtaHolidayCalendarCoverage WHERE id=1`);assertHolidayCoverage(now,new Date(now.getTime()+14*86400000),coverage.recordset[0]?.coverage_through??null);const ends=addBusinessDays(now,5,new Set(calendar.recordset.map(row=>row.holiday_date.toISOString().slice(0,10))));const req=pool.request();req.input("period",sql.UniqueIdentifier,request.params.id);req.input("report",sql.UniqueIdentifier,body.report_id);req.input("recipient",sql.NVarChar(320),body.recipient);req.input("method",sql.NVarChar(50),body.delivery_method);req.input("attestation",sql.NVarChar(1000),body.sender_attestation);req.input("actor",sql.NVarChar(200),auth.principal.userDetails??"onboard-console");req.input("now",sql.DateTime2,now);req.input("ends",sql.Date,ends);const result=await req.query<{changed:number}>(`IF EXISTS(SELECT 1 FROM ComplianceReports r JOIN AssessmentPeriods p ON p.id=r.period_id WHERE r.id=@report AND r.period_id=@period AND r.issuance_type='preliminary' AND r.generated_at>=p.computed_at AND r.version=(SELECT MAX(version) FROM ComplianceReports WHERE period_id=@period AND issuance_type='preliminary')) AND NOT EXISTS(SELECT 1 FROM PeriodKpiAssessments WHERE period_id=@period AND (recommended_action IS NULL OR reviewed_input_sha256<>input_sha256)) BEGIN INSERT ValidationDraftShares(period_id,report_id,recipient,delivery_method,sender_attestation,shared_by,shared_at,validation_ends_on) VALUES(@period,@report,@recipient,@method,@attestation,@actor,@now,@ends);UPDATE AssessmentPeriods SET status='in_validation',validation_shared_at=@now,validation_ends_on=@ends,validation_shared_by=@actor,validation_recipient=@recipient,validation_method=@method,validation_attestation=@attestation WHERE id=@period AND status='in_review';SELECT @@ROWCOUNT changed;END`);if(!result.recordset[0]?.changed)return{status:409,jsonBody:{error:"The latest fully reviewed Validation Draft for the current computation is required"}};return{status:200,jsonBody:{id:request.params.id,status:"in_validation",validation_ends_on:ends.toISOString().slice(0,10)}};}catch(error){context.error("POST validation share failed",error);return{status:409,jsonBody:{error:error instanceof Error?error.message:"Unable to share Validation Draft"}};}
}});

app.http("assessmentCapsList",{route:"assessment-caps",methods:["GET"],authLevel:"anonymous",handler:async(request,context)=>{
  const auth=requireRole(request,COMPLIANCE_READ_ROLES);if(!auth.authorized)return{status:auth.status,jsonBody:{error:auth.message}};const period=request.query.get("period_id");if(!isGuid(period))return{status:400,jsonBody:{error:"period_id is required"}};
  try{const pool=await getPool();const req=pool.request();req.input("period",sql.UniqueIdentifier,period);const result=await req.query(`SELECT c.*,s.name standard_name FROM CorrectiveActionPlans c LEFT JOIN ContractorPerformanceStandards s ON s.id=c.standard_id WHERE c.period_id=@period ORDER BY c.due_at`);return{status:200,jsonBody:{caps:result.recordset}};}catch(error){context.error("GET assessment CAPs failed",error);return{status:500,jsonBody:{error:"Internal server error"}};}
}});

app.http("assessmentDisputesList",{route:"assessment-disputes",methods:["GET"],authLevel:"anonymous",handler:async(request,context)=>{
  const auth=requireRole(request,COMPLIANCE_READ_ROLES);if(!auth.authorized)return{status:auth.status,jsonBody:{error:auth.message}};const period=request.query.get("period_id");if(!isGuid(period))return{status:400,jsonBody:{error:"period_id is required"}};
  try{const pool=await getPool();const req=pool.request();req.input("period",sql.UniqueIdentifier,period);const result=await req.query(`SELECT d.*,r.version report_version,(SELECT COUNT(*) FROM AssessmentDisputeItems i WHERE i.dispute_id=d.id) item_count FROM PenaltyDisputes d JOIN ComplianceReports r ON r.id=d.report_id WHERE r.period_id=@period ORDER BY d.created_at DESC`);return{status:200,jsonBody:{disputes:result.recordset}};}catch(error){context.error("GET assessment disputes failed",error);return{status:500,jsonBody:{error:"Internal server error"}};}
}});

app.http("assessmentDisputesCreate",{route:"assessment-disputes",methods:["POST"],authLevel:"anonymous",handler:async(request,context)=>{
  const auth=requireRole(request,COMPLIANCE_WRITE_ROLES);if(!auth.authorized)return{status:auth.status,jsonBody:{error:auth.message}};let body:Record<string,unknown>;try{body=await request.json() as Record<string,unknown>;}catch{return{status:400,jsonBody:{error:"Request body must be valid JSON"}};}
  const ids=Array.isArray(body.assessment_ids)?body.assessment_ids.filter(isGuid):[];if(!isGuid(body.report_id)||!ids.length||typeof body.basis!=="string"||!body.basis.trim())return{status:400,jsonBody:{error:"report_id, assessment_ids, and basis are required"}};
  try{const pool=await getPool();const reportReq=pool.request();reportReq.input("report",sql.UniqueIdentifier,body.report_id);const report=(await reportReq.query<any>(`SELECT * FROM ComplianceReports WHERE id=@report AND issued_at IS NOT NULL`)).recordset[0];if(!report)return{status:409,jsonBody:{error:"An issued Final Assessment is required"}};for(const assessmentId of ids){const check=pool.request();check.input("assessment",sql.UniqueIdentifier,assessmentId);check.input("report",sql.UniqueIdentifier,body.report_id);const valid=(await check.query<{valid:number}>(`SELECT COUNT(*) valid FROM PeriodKpiAssessments a JOIN ComplianceReports r ON r.period_id=a.period_id WHERE a.id=@assessment AND r.id=@report`)).recordset[0]?.valid;if(!valid)return{status:409,jsonBody:{error:"Every disputed Assessment Item must belong to the issued Final Assessment"}};}const id=crypto.randomUUID();const req=pool.request();req.input("id",sql.UniqueIdentifier,id);req.input("report",sql.UniqueIdentifier,body.report_id);req.input("assessment",sql.UniqueIdentifier,ids[0]);req.input("contractor",sql.UniqueIdentifier,report.contractor_id);req.input("submitted",sql.DateTime2,new Date());req.input("deadline",sql.DateTime2,report.dispute_deadline_at);req.input("basis",sql.NVarChar(sql.MAX),body.basis);req.input("actor",sql.NVarChar(200),auth.principal.userDetails??"onboard-console");await req.query(`INSERT PenaltyDisputes(id,assessment_id,contractor_id,submitted_at,notice_deadline_at,basis,completeness,status,created_by,report_id) VALUES(@id,@assessment,@contractor,@submitted,@deadline,@basis,'complete','submitted',@actor,@report)`);for(const assessmentId of ids){const item=pool.request();item.input("dispute",sql.UniqueIdentifier,id);item.input("assessment",sql.UniqueIdentifier,assessmentId);await item.query(`INSERT AssessmentDisputeItems(dispute_id,assessment_id) VALUES(@dispute,@assessment)`);}return{status:201,jsonBody:{id}};}catch(error){context.error("POST assessment dispute failed",error);return{status:409,jsonBody:{error:error instanceof Error?error.message:"Unable to create dispute"}};}
}});

app.http("assessmentDisputeDecide",{route:"assessment-disputes/{id}/decision",methods:["POST"],authLevel:"anonymous",handler:async(request,context)=>{
  const auth=requireRole(request,COMPLIANCE_MANAGER_ROLES);if(!auth.authorized)return{status:auth.status,jsonBody:{error:auth.message}};if(!isGuid(request.params.id))return{status:400,jsonBody:{error:"Invalid dispute id"}};let body:Record<string,unknown>;try{body=await request.json() as Record<string,unknown>;}catch{return{status:400,jsonBody:{error:"Request body must be valid JSON"}};}
  if(!["upheld","adjusted","rescinded","superseded"].includes(String(body.outcome))||typeof body.note!=="string"||!body.note.trim()||((body.outcome==="adjusted"||body.outcome==="rescinded")&&(typeof body.credit_amount!=="number"||body.credit_amount<0)))return{status:400,jsonBody:{error:"outcome, note, and any non-negative credit_amount are required"}};
  try{const pool=await getPool();const req=pool.request();req.input("id",sql.UniqueIdentifier,request.params.id);req.input("outcome",sql.NVarChar(30),body.outcome);req.input("note",sql.NVarChar(sql.MAX),body.note);req.input("actor",sql.NVarChar(200),auth.principal.userDetails??"onboard-console");req.input("credit",sql.Decimal(12,2),body.credit_amount??0);const result=await req.query<{changed:number}>(`UPDATE PenaltyDisputes SET status=@outcome,outcome=@outcome,determination_note=@note,decided_by=@actor,decided_at=SYSUTCDATETIME() WHERE id=@id AND status IN('submitted','under_review');DECLARE @changed INT=@@ROWCOUNT;IF @changed=1 AND @credit>0 INSERT AssessmentCredits(dispute_id,report_id,amount,reason,created_by) SELECT id,report_id,@credit,@note,@actor FROM PenaltyDisputes WHERE id=@id;SELECT @changed changed;`);if(!result.recordset[0]?.changed)return{status:409,jsonBody:{error:"Only an open dispute can be decided"}};return{status:200,jsonBody:{id:request.params.id,status:body.outcome}};}catch(error){context.error("POST dispute decision failed",error);return{status:500,jsonBody:{error:"Internal server error"}};}
}});
