import { createHash, randomUUID } from "node:crypto";
import { app, type HttpRequest, type InvocationContext } from "@azure/functions";
import { addBusinessDays, assertHolidayCoverage } from "../lib/assessment/businessDays";
import { COMPLIANCE_MANAGER_ROLES, COMPLIANCE_READ_ROLES, COMPLIANCE_WRITE_ROLES, requireRole } from "../lib/auth";
import { buildComplianceReportBlobPath, downloadComplianceReport, uploadComplianceReport } from "../lib/blobStorage";
import { getPool, sql } from "../lib/db";
import { renderAssessmentReport, type AssessmentReportModel } from "../lib/report/renderAssessmentReport";
import { isGuid } from "../lib/validation";

async function readModel(periodId:string,reportId:string,type:"preliminary"|"final",version:number,issuedAt:Date|null,deadline:Date|null):Promise<AssessmentReportModel>{
  const pool=await getPool();const req=pool.request();req.input("period",sql.UniqueIdentifier,periodId);
  const period=await req.query<any>(`SELECT p.*,c.name contractor_name FROM AssessmentPeriods p JOIN Contractors c ON c.id=p.contractor_id WHERE p.id=@period`);
  const p=period.recordset[0];if(!p)throw new Error("Assessment Period not found");
  const rows=await req.query<any>(`SELECT a.*,s.name,s.standard_type FROM PeriodKpiAssessments a JOIN AssessmentPeriodStandards s ON s.period_id=a.period_id AND s.standard_id=a.standard_id WHERE a.period_id=@period ORDER BY s.sort_order`);
  return{reportId,issuanceType:type,version,contractorName:p.contractor_name,serviceMonth:p.service_month,issuedAt:issuedAt?.toISOString()??null,issuedBy:null,disputeDeadline:deadline?.toISOString().slice(0,10)??null,isPartial:Boolean(p.is_partial),assessedTotal:Number(type==="final"?p.final_total??0:p.proposed_total??0),assessments:rows.recordset.map((a:any)=>({name:a.name,standardType:a.standard_type,metricDisplay:a.assessment_outcome==="not_assessable"?"Not Assessable":a.metric_display,targetDisplay:a.target_display,tierLabel:a.tier_label,occurrenceCount:a.occurrence_count,baseAmount:Number(a.base_amount),reliefAmount:Number(a.relief_amount),escalationMultiplier:Number(a.escalation_multiplier),assessedAmount:Number(type==="final"?a.final_amount??0:a.proposed_amount),managerAction:a.manager_action,managerReason:a.manager_reason,dataCompletenessPct:a.data_completeness_pct}))};
}

app.http("assessmentReportsList",{route:"assessment-reports",methods:["GET"],authLevel:"anonymous",handler:async(request,context)=>{
  const auth=requireRole(request,COMPLIANCE_READ_ROLES);if(!auth.authorized)return{status:auth.status,jsonBody:{error:auth.message}};
  const period=request.query.get("period_id");if(!isGuid(period))return{status:400,jsonBody:{error:"period_id is required"}};
  try{const pool=await getPool();const req=pool.request();req.input("period",sql.UniqueIdentifier,period);const result=await req.query(`SELECT id,period_id,service_month,issuance_type,version,supersedes_id,content_sha256,assessed_total,issued_at,issued_by,dispute_deadline_at,supersede_reason,generated_by,generated_at FROM ComplianceReports WHERE period_id=@period ORDER BY generated_at DESC`);return{status:200,jsonBody:{reports:result.recordset}};}catch(error){context.error("GET assessment reports failed",error);return{status:500,jsonBody:{error:"Internal server error"}};}
}});

app.http("assessmentReportsCreate",{route:"assessment-reports",methods:["POST"],authLevel:"anonymous",handler:async(request,context)=>{
  let body:Record<string,unknown>;try{body=await request.json() as Record<string,unknown>;}catch{return{status:400,jsonBody:{error:"Request body must be valid JSON"}};}
  const type=body.issuance_type;if(type!=="preliminary"&&type!=="final")return{status:400,jsonBody:{error:"issuance_type must be preliminary or final"}};
  const auth=requireRole(request,type==="final"?COMPLIANCE_MANAGER_ROLES:COMPLIANCE_WRITE_ROLES);if(!auth.authorized)return{status:auth.status,jsonBody:{error:auth.message}};
  if(!isGuid(body.period_id))return{status:400,jsonBody:{error:"period_id is required"}};
  try{
    const pool=await getPool();const state=pool.request();state.input("period",sql.UniqueIdentifier,body.period_id);
    const info=await state.query<any>(`SELECT p.*,(SELECT TOP 1 id FROM ComplianceReports WHERE period_id=p.id AND issuance_type='final' ORDER BY version DESC) latest_final FROM AssessmentPeriods p WHERE p.id=@period`);const p=info.recordset[0];
    if(!p)return{status:404,jsonBody:{error:"Assessment Period not found"}};
    if(type==="preliminary"&&p.status!=="in_review")return{status:409,jsonBody:{error:"A Validation Draft requires a reviewed Assessment Period"}};
    if(type==="final"&&p.status!=="finalized")return{status:409,jsonBody:{error:"A Final Assessment requires a Finalized Assessment"}};
    if(type==="final"&&p.latest_final&&(body.supersedes_id!==p.latest_final||typeof body.supersede_reason!=="string"||!body.supersede_reason.trim()))return{status:409,jsonBody:{error:"A Superseding Final Assessment requires the latest assessment and a reason"}};
    const versionReq=pool.request();versionReq.input("period",sql.UniqueIdentifier,body.period_id);versionReq.input("type",sql.NVarChar(20),type);const version=(await versionReq.query<{version:number}>(`SELECT ISNULL(MAX(version),0)+1 version FROM ComplianceReports WHERE period_id=@period AND issuance_type=@type`)).recordset[0].version;
    const id=randomUUID();const model=await readModel(body.period_id,id,type,version,null,null);const html=renderAssessmentReport(model);const hash=createHash("sha256").update(html).digest("hex");const path=buildComplianceReportBlobPath(body.period_id,id);await uploadComplianceReport(path,html);
    const write=pool.request();write.input("id",sql.UniqueIdentifier,id);write.input("period",sql.UniqueIdentifier,body.period_id);write.input("contractor",sql.UniqueIdentifier,p.contractor_id);write.input("month",sql.Char(6),p.service_month);write.input("type",sql.NVarChar(20),type);write.input("version",sql.Int,version);write.input("supersedes",sql.UniqueIdentifier,body.supersedes_id??null);write.input("reason",sql.NVarChar(500),body.supersede_reason??null);write.input("path",sql.NVarChar(1000),path);write.input("hash",sql.Char(64),hash);write.input("total",sql.Decimal(12,2),model.assessedTotal);write.input("actor",sql.NVarChar(200),auth.principal.userDetails??"onboard-console");
    await write.query(`INSERT ComplianceReports(id,period_id,contractor_id,service_month,issuance_type,version,supersedes_id,blob_path,content_sha256,assessed_total,supersede_reason,generated_by) VALUES(@id,@period,@contractor,@month,@type,@version,@supersedes,@path,@hash,@total,@reason,@actor)`);
    return{status:201,jsonBody:{id,version,content_sha256:hash}};
  }catch(error){context.error("POST assessment report failed",error);return{status:409,jsonBody:{error:error instanceof Error?error.message:"Report generation failed"}};}
}});

async function streamReport(request:HttpRequest,attachment:boolean,context:InvocationContext){
  const auth=requireRole(request,COMPLIANCE_READ_ROLES);if(!auth.authorized)return{status:auth.status,jsonBody:{error:auth.message}};if(!isGuid(request.params.id))return{status:400,jsonBody:{error:"Invalid report id"}};
  try{const pool=await getPool();const req=pool.request();req.input("id",sql.UniqueIdentifier,request.params.id);const row=(await req.query<any>(`SELECT blob_path,content_sha256,service_month,issuance_type,version FROM ComplianceReports WHERE id=@id`)).recordset[0];if(!row)return{status:404,jsonBody:{error:"Report not found"}};const bytes=await downloadComplianceReport(row.blob_path);if(createHash("sha256").update(bytes).digest("hex")!==row.content_sha256)throw new Error("Archived report hash mismatch");return{status:200,headers:{"content-type":"text/html; charset=utf-8","content-disposition":`${attachment?"attachment":"inline"}; filename="assessment-${row.service_month}-${row.issuance_type}-v${row.version}.html"`},body:bytes};}catch(error){context.error("GET assessment report content failed",error);return{status:500,jsonBody:{error:"Unable to retrieve verified report"}};}
}
app.http("assessmentReportHtml",{route:"assessment-reports/{id}/html",methods:["GET"],authLevel:"anonymous",handler:(r,c)=>streamReport(r,false,c)});
app.http("assessmentReportDownload",{route:"assessment-reports/{id}/download",methods:["GET"],authLevel:"anonymous",handler:(r,c)=>streamReport(r,true,c)});

app.http("assessmentReportIssue",{route:"assessment-reports/{id}/issue",methods:["POST"],authLevel:"anonymous",handler:async(request,context)=>{
  const auth=requireRole(request,COMPLIANCE_MANAGER_ROLES);if(!auth.authorized)return{status:auth.status,jsonBody:{error:auth.message}};if(!isGuid(request.params.id))return{status:400,jsonBody:{error:"Invalid report id"}};
  let body:Record<string,unknown>;try{body=await request.json() as Record<string,unknown>;}catch{return{status:400,jsonBody:{error:"Request body must be valid JSON"}};}
  if(![body.recipient,body.delivery_method,body.sender_attestation].every(value=>typeof value==="string"&&value.trim()))return{status:400,jsonBody:{error:"recipient, delivery_method, and sender_attestation are required"}};
  try{
    const pool=await getPool();const actor=auth.principal.userDetails??"onboard-console";const lookup=pool.request();lookup.input("id",sql.UniqueIdentifier,request.params.id);lookup.input("actor",sql.NVarChar(200),actor);const row=(await lookup.query<any>(`SELECT r.* FROM ComplianceReports r JOIN AssessmentPeriods p ON p.id=r.period_id WHERE r.id=@id AND r.issuance_type='final' AND r.issued_at IS NULL AND p.status='finalized' AND NOT EXISTS(SELECT 1 FROM PeriodKpiAssessments a WHERE a.period_id=p.id AND a.reviewed_by=@actor)`)).recordset[0];if(!row)return{status:409,jsonBody:{error:"Issuance requires an unissued Final Assessment and an issuer who did not review any Assessment Item"}};
    const issuedAt=new Date();const calendar=await pool.request().query<{holiday_date:Date}>(`SELECT holiday_date FROM MvtaHolidays`);const coverage=await pool.request().query<{coverage_through:Date}>(`SELECT coverage_through FROM MvtaHolidayCalendarCoverage WHERE id=1`);assertHolidayCoverage(issuedAt,new Date(issuedAt.getTime()+30*86400000),coverage.recordset[0]?.coverage_through??null);const holidays=new Set(calendar.recordset.map(r=>r.holiday_date.toISOString().slice(0,10)));const deadline=addBusinessDays(issuedAt,10,holidays);const capDeadline=addBusinessDays(issuedAt,5,holidays);
    const model=await readModel(row.period_id,row.id,"final",row.version,issuedAt,deadline);model.issuedBy=actor;const html=renderAssessmentReport(model);const hash=createHash("sha256").update(html).digest("hex");const issuedPath=row.blob_path.replace(/\.html$/,`-issued-${issuedAt.getTime()}.html`);await uploadComplianceReport(issuedPath,html);
    const write=pool.request();write.input("id",sql.UniqueIdentifier,row.id);write.input("period",sql.UniqueIdentifier,row.period_id);write.input("actor",sql.NVarChar(200),actor);write.input("issued",sql.DateTime2,issuedAt);write.input("deadline",sql.DateTime2,deadline);write.input("cap_deadline",sql.DateTime2,capDeadline);write.input("path",sql.NVarChar(1000),issuedPath);write.input("hash",sql.Char(64),hash);write.input("recipient",sql.NVarChar(320),body.recipient);write.input("method",sql.NVarChar(50),body.delivery_method);write.input("attestation",sql.NVarChar(1000),body.sender_attestation);
    const result=await write.query<{changed:number}>(`UPDATE ComplianceReports SET issued_at=@issued,issued_by=@actor,dispute_deadline_at=@deadline,blob_path=@path,content_sha256=@hash WHERE id=@id AND issued_at IS NULL;DECLARE @changed INT=@@ROWCOUNT;IF @changed=1 BEGIN INSERT FinalIssuanceRecords(report_id,recipient,delivery_method,sender_attestation,issued_by,issued_at,content_sha256) VALUES(@id,@recipient,@method,@attestation,@actor,@issued,@hash);UPDATE AssessmentPeriods SET status='issued' WHERE id=@period;INSERT CorrectiveActionPlans(contractor_id,standard_id,period_id,trigger_reason,due_at,created_by) SELECT p.contractor_id,a.standard_id,@period,'tier_rule',@cap_deadline,@actor FROM PeriodKpiAssessments a JOIN AssessmentPeriods p ON p.id=a.period_id WHERE a.period_id=@period AND a.cap_required=1 AND NOT EXISTS(SELECT 1 FROM CorrectiveActionPlans c WHERE c.period_id=@period AND c.standard_id=a.standard_id);INSERT ComplianceAssessmentAudit(entity_type,entity_id,action,actor,after_json) VALUES('report',@id,'issued',@actor,CONCAT('{"content_sha256":"',@hash,'"}'));END SELECT @changed changed;`);
    if(!result.recordset[0]?.changed)return{status:409,jsonBody:{error:"Final Assessment was issued concurrently"}};return{status:200,jsonBody:{id:row.id,status:"issued",content_sha256:hash,dispute_deadline_at:deadline.toISOString()}};
  }catch(error){context.error("POST issue report failed",error);return{status:409,jsonBody:{error:error instanceof Error?error.message:"Final Assessment issuance failed"}};}
}});
