import { app } from "@azure/functions";
import { COMPLIANCE_READ_ROLES, COMPLIANCE_WRITE_ROLES, requireRole } from "../lib/auth";
import { buildComplianceEvidenceBlobPath, getComplianceEvidenceUploadSasUrl } from "../lib/blobStorage";
import { getPool, sql } from "../lib/db";
import { isGuid } from "../lib/validation";

app.http("assessmentEvidenceList",{route:"assessment-evidence",methods:["GET"],authLevel:"anonymous",handler:async(request,context)=>{const auth=requireRole(request,COMPLIANCE_READ_ROLES);if(!auth.authorized)return{status:auth.status,jsonBody:{error:auth.message}};const assessment=request.query.get("assessment_id");if(!isGuid(assessment))return{status:400,jsonBody:{error:"assessment_id is required"}};try{const pool=await getPool();const req=pool.request();req.input("assessment",sql.UniqueIdentifier,assessment);const result=await req.query(`SELECT id,assessment_id,content_type,file_size_bytes,caption,content_sha256,supersedes_id,visibility,redaction_reason,uploaded_by,uploaded_at FROM ComplianceEvidence WHERE assessment_id=@assessment ORDER BY uploaded_at DESC`);return{status:200,jsonBody:{evidence:result.recordset}};}catch(error){context.error("GET assessment evidence failed",error);return{status:500,jsonBody:{error:"Internal server error"}};}}});

app.http("assessmentEvidenceUploadUrl",{route:"assessment-evidence/upload-url",methods:["POST"],authLevel:"anonymous",handler:async(request,context)=>{const auth=requireRole(request,COMPLIANCE_WRITE_ROLES);if(!auth.authorized)return{status:auth.status,jsonBody:{error:auth.message}};let body:Record<string,unknown>;try{body=await request.json() as Record<string,unknown>;}catch{return{status:400,jsonBody:{error:"Request body must be valid JSON"}};}if(!isGuid(body.assessment_id)||typeof body.file_name!=="string"||!body.file_name.trim())return{status:400,jsonBody:{error:"assessment_id and file_name are required"}};try{const blobPath=buildComplianceEvidenceBlobPath(body.assessment_id,body.file_name);return{status:200,jsonBody:{upload_url:await getComplianceEvidenceUploadSasUrl(blobPath),blob_path:blobPath}};}catch(error){context.error("POST assessment evidence upload URL failed",error);return{status:500,jsonBody:{error:"Evidence storage is unavailable"}};}}});

app.http("assessmentEvidenceCreate",{route:"assessment-evidence",methods:["POST"],authLevel:"anonymous",handler:async(request,context)=>{const auth=requireRole(request,COMPLIANCE_WRITE_ROLES);if(!auth.authorized)return{status:auth.status,jsonBody:{error:auth.message}};let body:Record<string,unknown>;try{body=await request.json() as Record<string,unknown>;}catch{return{status:400,jsonBody:{error:"Request body must be valid JSON"}};}if(!isGuid(body.assessment_id)||typeof body.blob_path!=="string"||typeof body.content_type!=="string"||typeof body.file_size_bytes!=="number"||body.file_size_bytes<=0||typeof body.content_sha256!=="string"||!/^[a-f0-9]{64}$/i.test(body.content_sha256)||!["internal","contractor"].includes(String(body.visibility)))return{status:400,jsonBody:{error:"Valid assessment, blob, content, hash, size, and visibility are required"}};try{const pool=await getPool();const req=pool.request();req.input("assessment",sql.UniqueIdentifier,body.assessment_id);req.input("path",sql.NVarChar(1000),body.blob_path);req.input("type",sql.NVarChar(200),body.content_type);req.input("size",sql.BigInt,body.file_size_bytes);req.input("caption",sql.NVarChar(500),body.caption??null);req.input("hash",sql.Char(64),body.content_sha256);req.input("visibility",sql.NVarChar(20),body.visibility);req.input("redaction",sql.NVarChar(1000),body.redaction_reason??null);req.input("actor",sql.NVarChar(200),auth.principal.userDetails??"onboard-console");const result=await req.query<{id:string}>(`IF EXISTS(SELECT 1 FROM PeriodKpiAssessments WHERE id=@assessment) BEGIN DECLARE @id UNIQUEIDENTIFIER=NEWID();INSERT ComplianceEvidence(id,assessment_id,blob_path,content_type,file_size_bytes,caption,uploaded_by,content_sha256,visibility,redaction_reason) VALUES(@id,@assessment,@path,@type,@size,@caption,@actor,@hash,@visibility,@redaction);INSERT ComplianceAssessmentAudit(entity_type,entity_id,action,actor,after_json) VALUES('assessment',@assessment,'evidence_added',@actor,CONCAT('{"evidence_id":"',@id,'","sha256":"',@hash,'"}'));SELECT @id id;END`);if(!result.recordset[0])return{status:404,jsonBody:{error:"Assessment Item not found"}};return{status:201,jsonBody:result.recordset[0]};}catch(error){context.error("POST assessment evidence failed",error);return{status:500,jsonBody:{error:"Internal server error"}};}}});
