import { app, type HttpRequest, type InvocationContext } from "@azure/functions";
import { COMPLIANCE_READ_ROLES, COMPLIANCE_WRITE_ROLES, requireRole } from "../lib/auth";
import { getPool, sql } from "../lib/db";
import { isGuid, validateComplianceOccurrence } from "../lib/validation";

app.http("complianceOccurrencesList", { route:"compliance-occurrences",methods:["GET"],authLevel:"anonymous",handler:async(request:HttpRequest,context:InvocationContext)=>{
  const auth=requireRole(request,COMPLIANCE_READ_ROLES);if(!auth.authorized)return{status:auth.status,jsonBody:{error:auth.message}};
  try{const pool=await getPool();const check=await pool.request().query<{ready:number}>(`SELECT CASE WHEN OBJECT_ID('dbo.ComplianceOccurrences','U') IS NULL THEN 0 ELSE 1 END ready`);if(!check.recordset[0]?.ready)return{status:200,jsonBody:{occurrences:[],diagnostics:{table_ready:false}}};const result=await pool.request().query(`SELECT o.*,s.code standard_code,s.name standard_name,c.name contractor_name FROM ComplianceOccurrences o JOIN ContractorPerformanceStandards s ON s.id=o.standard_id JOIN Contractors c ON c.id=o.contractor_id ORDER BY o.service_date DESC,o.created_at DESC`);return{status:200,jsonBody:{occurrences:result.recordset,diagnostics:{table_ready:true}}};}
  catch(error){context.error("GET compliance occurrences failed",error);return{status:500,jsonBody:{error:"Internal server error"}};}
}});

app.http("complianceOccurrencesCreate", { route:"compliance-occurrences",methods:["POST"],authLevel:"anonymous",handler:async(request:HttpRequest,context:InvocationContext)=>{
  const auth=requireRole(request,COMPLIANCE_WRITE_ROLES);if(!auth.authorized)return{status:auth.status,jsonBody:{error:auth.message}};let body:Record<string,unknown>;try{body=await request.json() as Record<string,unknown>;}catch{return{status:400,jsonBody:{error:"Request body must be valid JSON"}};}const errors=validateComplianceOccurrence(body);if(errors.length)return{status:400,jsonBody:{error:"Validation failed",details:errors}};
  const pool=await getPool();const tx=new sql.Transaction(pool);try{await tx.begin();const req=new sql.Request(tx);const id=crypto.randomUUID();req.input("id",sql.UniqueIdentifier,id);req.input("standard",sql.UniqueIdentifier,body.standard_id);req.input("contractor",sql.UniqueIdentifier,body.contractor_id);req.input("date",sql.Char(8),body.service_date);req.input("quantity",sql.Int,body.quantity??1);req.input("duration",sql.Int,body.duration_days??null);req.input("qualifier",sql.NVarChar(50),body.qualifier_code??null);req.input("description",sql.NVarChar(2000),String(body.description).trim());req.input("actor",sql.NVarChar(200),auth.principal.userDetails??"onboard-console");await req.query(`INSERT ComplianceOccurrences(id,standard_id,contractor_id,service_date,quantity,duration_days,qualifier_code,description,source,review_status,attribution,created_by) VALUES(@id,@standard,@contractor,@date,@quantity,@duration,@qualifier,@description,'manual','confirmed','contractor_error',@actor); UPDATE AssessmentPeriods SET input_revision=input_revision+1,status=CASE WHEN status IN('in_review','stale') THEN 'stale' ELSE status END WHERE contractor_id=@contractor AND service_month=LEFT(@date,6) AND status<>'finalized';`);await tx.commit();return{status:201,jsonBody:{id}};}
  catch(error){try{await tx.rollback();}catch{/*done*/}context.error("POST compliance occurrence failed",error);return{status:500,jsonBody:{error:"Internal server error"}};}
}});

app.http("complianceOccurrencePatch", { route:"compliance-occurrences/{id}",methods:["PATCH"],authLevel:"anonymous",handler:async(request:HttpRequest,context:InvocationContext)=>{
  const auth=requireRole(request,COMPLIANCE_WRITE_ROLES);if(!auth.authorized)return{status:auth.status,jsonBody:{error:auth.message}};if(!isGuid(request.params.id))return{status:400,jsonBody:{error:"Invalid occurrence id"}};let body:Record<string,unknown>;try{body=await request.json() as Record<string,unknown>;}catch{return{status:400,jsonBody:{error:"Request body must be valid JSON"}};}if(!["candidate","confirmed","dismissed"].includes(String(body.review_status))||!["contractor_error","excusable","mvta_directed","undetermined"].includes(String(body.attribution)))return{status:400,jsonBody:{error:"Valid review_status and attribution are required"}};
  const pool=await getPool();const tx=new sql.Transaction(pool);try{await tx.begin();const req=new sql.Request(tx);req.input("id",sql.UniqueIdentifier,request.params.id);req.input("status",sql.NVarChar(20),body.review_status);req.input("attribution",sql.NVarChar(30),body.attribution);req.input("reason",sql.NVarChar(1000),body.dismiss_reason??null);req.input("actor",sql.NVarChar(200),auth.principal.userDetails??"onboard-console");const result=await req.query<{contractor_id:string;service_month:string}>(`UPDATE ComplianceOccurrences SET review_status=@status,attribution=@attribution,dismiss_reason=@reason,reviewed_by=@actor,reviewed_at=SYSUTCDATETIME() OUTPUT inserted.contractor_id,inserted.service_month WHERE id=@id;`);const row=result.recordset[0];if(!row){await tx.rollback();return{status:404,jsonBody:{error:"Occurrence not found"}};}const stale=new sql.Request(tx);stale.input("contractor",sql.UniqueIdentifier,row.contractor_id);stale.input("month",sql.Char(6),row.service_month);await stale.query(`UPDATE AssessmentPeriods SET input_revision=input_revision+1,status=CASE WHEN status IN('in_review','stale') THEN 'stale' ELSE status END WHERE contractor_id=@contractor AND service_month=@month AND status<>'finalized';`);await tx.commit();return{status:200,jsonBody:{id:request.params.id}};}
  catch(error){try{await tx.rollback();}catch{/*done*/}context.error("PATCH compliance occurrence failed",error);return{status:500,jsonBody:{error:"Internal server error"}};}
}});
