import { app, type InvocationContext } from "@azure/functions";
import { getPool, sql } from "../lib/db";

interface CrossingMessage { crossing_id: number }
app.serviceBusQueue("eventGeofenceNotify", { connection: "ServiceBusConnection", queueName: "event-geofence-notifications", handler: async (message: unknown, context: InvocationContext) => {
  const id = (message as CrossingMessage).crossing_id; const pool = await getPool(); const r = pool.request(); r.input("id", sql.BigInt, id);
  const row = (await r.query(`SELECT c.*, g.name geofence_name, matched.send_mode FROM EventGeofenceCrossings c JOIN EventGeofences g ON g.id=c.geofence_id OUTER APPLY (SELECT TOP 1 rule.send_mode FROM EventGeofenceDirectionRules rule WHERE rule.geofence_id=c.geofence_id AND rule.transition=c.transition AND ((rule.heading_min <= rule.heading_max AND c.heading_at_crossing BETWEEN rule.heading_min AND rule.heading_max) OR (rule.heading_min > rule.heading_max AND (c.heading_at_crossing >= rule.heading_min OR c.heading_at_crossing <= rule.heading_max))) ORDER BY rule.sort_order,rule.id) matched WHERE c.id=@id`)).recordset[0] as { vehicle_id:number; transition:string; geofence_name:string; destination_label:string|null; send_mode:string } | undefined;
  if (!row || !row.send_mode) { context.log(`No direction rule matched crossing ${id}; no notification queued.`); return; }
  const body = `Event vehicle ${row.vehicle_id} ${row.transition}ed ${row.geofence_name}${row.destination_label ? `; ${row.destination_label}` : ""}.`; const insert = pool.request(); insert.input("crossing", sql.BigInt, id); insert.input("mode", sql.NVarChar, row.send_mode); insert.input("body", sql.NVarChar, body); const notification = (await insert.query("INSERT INTO EventGeofenceNotifications(crossing_id,send_mode,message_body,status) OUTPUT INSERTED.id VALUES(@crossing,@mode,@body,'pending')")).recordset[0];
  if (row.send_mode === "auto" && process.env.TEAMS_EVENT_WEBHOOK_URL) { try { const response = await fetch(process.env.TEAMS_EVENT_WEBHOOK_URL, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ text: body }) }); if (response.ok) await pool.request().input("id", sql.UniqueIdentifier, notification.id).query("UPDATE EventGeofenceNotifications SET status='sent',sent_by='event-geofence-notify',sent_at=SYSUTCDATETIME() WHERE id=@id AND status='pending'"); else context.error(`Teams webhook returned ${response.status}`); } catch (err) { context.error("Teams event notification failed", err); } }
  context.log(`Event geofence notification ${notification.id} created.`);
} });
