import { app, type HttpRequest, type InvocationContext } from "@azure/functions";
import { COMPLIANCE_READ_ROLES, COMPLIANCE_WRITE_ROLES, requireRole } from "../lib/auth";
import { getPool, sql } from "../lib/db";
import { writeManualMetric } from "../lib/assessment/manualMetricWrite";
import { isGuid, isServiceMonth, validateManualMetric } from "../lib/validation";

app.http("manualMetricsList", {route:"manual-metrics",methods:["GET"],authLevel:"anonymous",handler:async(request:HttpRequest,context:InvocationContext)=>{const auth=requireRole(request,COMPLIANCE_READ_ROLES);if(!auth.authorized)return{status:auth.status,jsonBody:{error:auth.message}};try{const pool=await getPool();const q=pool.request();const contractor=request.query.get("contractor_id"),month=request.query.get("service_month");const limit=Math.min(1000,Math.max(1,Number(request.query.get("limit")??500)||500));q.input("contractor",sql.UniqueIdentifier,isGuid(contractor)?contractor:null);q.input("month",sql.Char(6),isServiceMonth(month)?month:null);q.input("limit",sql.Int,limit);const result=await q.query(`SELECT TOP (@limit) m.*,s.code standard_code,s.name standard_name,c.name contractor_name FROM ManualMetricEntries m JOIN ContractorPerformanceStandards s ON s.id=m.standard_id JOIN Contractors c ON c.id=m.contractor_id WHERE m.superseded_by IS NULL AND (@contractor IS NULL OR m.contractor_id=@contractor) AND (@month IS NULL OR m.service_month=@month) ORDER BY m.service_month DESC,s.sort_order`);return{status:200,jsonBody:{metrics:result.recordset,diagnostics:{table_ready:true}}};}catch(error){context.error("GET manual metrics failed",error);return{status:500,jsonBody:{error:"Internal server error"}};}}});

app.http("manualMetricsPut", {route:"manual-metrics",methods:["PUT"],authLevel:"anonymous",handler:async(request:HttpRequest,context:InvocationContext)=>{const auth=requireRole(request,COMPLIANCE_WRITE_ROLES);if(!auth.authorized)return{status:auth.status,jsonBody:{error:auth.message}};let body:Record<string,unknown>;try{body=await request.json() as Record<string,unknown>;}catch{return{status:400,jsonBody:{error:"Request body must be valid JSON"}};}const errors=validateManualMetric(body);if(errors.length)return{status:400,jsonBody:{error:errors.join("; ")}};
const pool=await getPool();const tx=new sql.Transaction(pool);try{await tx.begin();const {id}=await writeManualMetric(tx,{standardId:body.standard_id as string,contractorId:body.contractor_id as string,serviceMonth:body.service_month as string,metricValue:body.metric_value as number,numerator:body.numerator as number|null|undefined,denominator:body.denominator as number|null|undefined,unitCount:body.unit_count as number|null|undefined,sourceNote:body.source_note as string,enteredBy:auth.principal.userDetails??"onboard-console"});await tx.commit();return{status:200,jsonBody:{id}};}catch(error){try{await tx.rollback();}catch{/*done*/}context.error("PUT manual metric failed",error);return{status:500,jsonBody:{error:"Internal server error"}};}}});
