import { app, type HttpRequest, type InvocationContext } from "@azure/functions";
import { COMPLIANCE_READ_ROLES, COMPLIANCE_WRITE_ROLES, requireRole } from "../lib/auth";
import { getPool, sql } from "../lib/db";
import { isGuid, isServiceMonth, validateManualMetric } from "../lib/validation";

app.http("manualMetricsList", {route:"manual-metrics",methods:["GET"],authLevel:"anonymous",handler:async(request:HttpRequest,context:InvocationContext)=>{const auth=requireRole(request,COMPLIANCE_READ_ROLES);if(!auth.authorized)return{status:auth.status,jsonBody:{error:auth.message}};try{const pool=await getPool();const q=pool.request();const contractor=request.query.get("contractor_id"),month=request.query.get("service_month");const limit=Math.min(1000,Math.max(1,Number(request.query.get("limit")??500)||500));q.input("contractor",sql.UniqueIdentifier,isGuid(contractor)?contractor:null);q.input("month",sql.Char(6),isServiceMonth(month)?month:null);q.input("limit",sql.Int,limit);const result=await q.query(`SELECT TOP (@limit) m.*,s.code standard_code,s.name standard_name,c.name contractor_name FROM ManualMetricEntries m JOIN ContractorPerformanceStandards s ON s.id=m.standard_id JOIN Contractors c ON c.id=m.contractor_id WHERE m.superseded_by IS NULL AND (@contractor IS NULL OR m.contractor_id=@contractor) AND (@month IS NULL OR m.service_month=@month) ORDER BY m.service_month DESC,s.sort_order`);return{status:200,jsonBody:{metrics:result.recordset,diagnostics:{table_ready:true}}};}catch(error){context.error("GET manual metrics failed",error);return{status:500,jsonBody:{error:"Internal server error"}};}}});

app.http("manualMetricsPut", {route:"manual-metrics",methods:["PUT"],authLevel:"anonymous",handler:async(request:HttpRequest,context:InvocationContext)=>{const auth=requireRole(request,COMPLIANCE_WRITE_ROLES);if(!auth.authorized)return{status:auth.status,jsonBody:{error:auth.message}};let body:Record<string,unknown>;try{body=await request.json() as Record<string,unknown>;}catch{return{status:400,jsonBody:{error:"Request body must be valid JSON"}};}const errors=validateManualMetric(body);if(errors.length)return{status:400,jsonBody:{error:errors.join("; ")}};
const pool=await getPool();const tx=new sql.Transaction(pool);try{await tx.begin();const find=new sql.Request(tx);find.input("standard",sql.UniqueIdentifier,body.standard_id);find.input("contractor",sql.UniqueIdentifier,body.contractor_id);find.input("month",sql.Char(6),body.service_month);const current=await find.query<{id:string}>(`SELECT id FROM ManualMetricEntries WITH(UPDLOCK,HOLDLOCK) WHERE standard_id=@standard AND contractor_id=@contractor AND service_month=@month AND superseded_by IS NULL`);const id=crypto.randomUUID();const write=new sql.Request(tx);write.input("id",sql.UniqueIdentifier,id);write.input("standard",sql.UniqueIdentifier,body.standard_id);write.input("contractor",sql.UniqueIdentifier,body.contractor_id);write.input("month",sql.Char(6),body.service_month);write.input("value",sql.Float,body.metric_value);write.input("numerator",sql.Float,body.numerator??null);write.input("denominator",sql.Float,body.denominator??null);write.input("units",sql.Int,body.unit_count??null);write.input("note",sql.NVarChar(1000),body.source_note);write.input("actor",sql.NVarChar(200),auth.principal.userDetails??"onboard-console");await write.query(`INSERT ManualMetricEntries(id,standard_id,contractor_id,service_month,metric_value,numerator,denominator,unit_count,source_note,entered_by) VALUES(@id,@standard,@contractor,@month,@value,@numerator,@denominator,@units,@note,@actor);`);if(current.recordset[0]){const supersede=new sql.Request(tx);supersede.input("old",sql.UniqueIdentifier,current.recordset[0].id);supersede.input("new",sql.UniqueIdentifier,id);await supersede.query(`UPDATE ManualMetricEntries SET superseded_by=@new WHERE id=@old`);}const stale=new sql.Request(tx);stale.input("contractor",sql.UniqueIdentifier,body.contractor_id);stale.input("month",sql.Char(6),body.service_month);await stale.query(`UPDATE AssessmentPeriods SET input_revision=input_revision+1,status=CASE WHEN status IN('in_review','stale') THEN 'stale' ELSE status END WHERE contractor_id=@contractor AND service_month=@month AND status<>'finalized'`);await tx.commit();return{status:200,jsonBody:{id}};}catch(error){try{await tx.rollback();}catch{/*done*/}context.error("PUT manual metric failed",error);return{status:500,jsonBody:{error:"Internal server error"}};}}});
