import { useEffect, useMemo, useState } from "react";
import { ApiError, type EventServicePlan } from "@mvta/shared";
import { api } from "../config.js";

const steps: EventServicePlan["status"][] = ["draft", "review", "approved", "active", "completed"];

export function EventPlanning() {
  const [plans, setPlans] = useState<EventServicePlan[]>([]); const [selected, setSelected] = useState(""); const [name, setName] = useState(""); const [message, setMessage] = useState<string | null>(null);
  const load = () => api.getEventServicePlans().then(({ plans: rows }) => { setPlans(rows); if (!selected && rows[0]) setSelected(rows[0].id); }).catch((err) => setMessage(err instanceof ApiError ? err.message : "Could not load event plans."));
  useEffect(() => { void load(); }, []);
  const plan = plans.find((row) => row.id === selected); const links = plan?.links ?? [];
  const counts = useMemo(() => ({ routes: links.filter((link) => link.kind === "routes").length, geofences: links.filter((link) => link.kind === "geofences").length, locations: links.filter((link) => link.kind === "locations").length }), [links]);
  async function create() { if (!name.trim()) return; try { const row = await api.createEventServicePlan(name.trim()); setName(""); setSelected(row.id); setMessage("Draft event plan created. Configure its assets in Admin before submitting for review."); void load(); } catch (err) { setMessage(err instanceof ApiError ? err.message : "Could not create event plan."); } }
  async function transition(action: "submit-review" | "approve" | "advance" | "complete" | "suspend") { if (!plan) return; try { await api.transitionEventServicePlan(plan.id, action); setMessage(`Plan ${action === "submit-review" ? "submitted for review" : `${action}d`}.`); void load(); } catch (err) { setMessage(err instanceof ApiError ? err.message : "Could not update event plan."); } }
  const action = plan?.status === "draft" ? "submit-review" : plan?.status === "review" ? "approve" : plan?.status === "approved" ? "advance" : plan?.status === "active" ? "complete" : null;
  return <><div className="panel-header">Event Planning</div><div className="panel-body"><p className="panel-desc">Prepare event service plans before they affect live operations. Reusable locations and geofences remain managed in Admin; active crossings and notifications remain in Event Monitoring.</p>{message && <p className="muted">{message}</p>}<div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><input className="f" value={name} onChange={(e) => setName(e.target.value)} placeholder="New event plan name" /><button className="btn-sm" disabled={!name.trim()} onClick={() => void create()}>Create draft</button><select className="f" value={selected} onChange={(e) => setSelected(e.target.value)}><option value="">Select plan</option>{plans.map((row) => <option key={row.id} value={row.id}>{row.name} · {row.status}</option>)}</select></div></div>{plan && <><div className="panel-header" style={{ marginTop: 24 }}>Plan lifecycle</div><div className="panel-body"><div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>{steps.map((step) => <span key={step} className={step === plan.status ? "btn-sm" : "muted"} style={{ padding: "6px 10px", border: "1px solid #ccd6d1", borderRadius: 6 }}>{step}</span>)}</div><p className="muted">Current state: <strong>{plan.status}</strong></p>{action && <button className="btn-sm" disabled={action === "advance" && (counts.routes === 0 || counts.geofences === 0)} onClick={() => void transition(action)}>{action === "submit-review" ? "Submit for review" : action === "approve" ? "Approve plan" : action === "advance" ? "Activate plan" : "Complete plan"}</button>}{plan.status === "active" && <button className="btn-sm" onClick={() => void transition("suspend")}>Suspend operations</button>}{action === "advance" && (counts.routes === 0 || counts.geofences === 0) && <p className="muted">Activation requires at least one linked SpecialEvent route and geofence.</p>}</div><div className="panel-header" style={{ marginTop: 24 }}>Planned resources</div><div className="panel-body"><div style={{ display: "flex", gap: 24, flexWrap: "wrap" }}><strong>{counts.routes} routes</strong><strong>{counts.geofences} geofences</strong><strong>{counts.locations} locations</strong></div><p className="muted">Use the Admin map asset editor to create or link reusable resources. This workspace controls plan readiness and lifecycle.</p></div></>}</>;
}
