#!/usr/bin/env bash
#
# Apply pending SQL migrations to the dev database.
#
# There is no migration runner in this repo and no schema-version table - the
# number in a filename is how a human knows the order (functions-restapi/sql/README.md).
# Applying a batch by hand means opening the firewall, finding the admin
# password, running sqlcmd four times in the right order, checking the schema
# actually landed, and closing the firewall again. This walks that path and
# reverts only what it opened.
#
# UPDATING FOR A LATER BATCH: edit the MIGRATIONS array and the matching
# CHECK_* arrays below the stages marker. Every migration listed must declare
# itself re-runnable, because this script offers no way to tell which of them
# already ran - re-running a no-op is what makes that acceptable. A migration
# that is not re-runnable does not belong in this list; apply it by hand.
#
# WHAT THIS CANNOT DO: the SQL admin password lives in Key Vault
# kv-mvta-dev-mvta-jx4471, which is private-only and unreachable from a laptop,
# so you paste it. It is read into the shell, passed to sqlcmd through
# SQLCMDPASSWORD rather than -P so it stays out of `ps`, and never written to
# disk.
#
# Everything above the "STAGES" marker is the wizard library (generated by the
# /wizard skill): do not hand-edit it. The procedure is below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — apply the pending SQL migrations to the dev database.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Everything specific to this run lives here, so a later migration set is a
# one-line edit.
SQL_SERVER="sql-mvta-dev-mvta-jx4471"
SQL_FQDN="${SQL_SERVER}.database.windows.net"
SQL_DATABASE="sqldb-mvta-onboard-dev"
SQL_ADMIN="mvtaonboardadmin"
RESOURCE_GROUP="rg-mvta-onboard-dev"
SQL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/functions-restapi/sql"

MIGRATIONS=(
  "migration-103-period-resolver-key.sql"
  "migration-104-measurement-source-kinds.sql"
  "migration-105-reference-values.sql"
  "migration-106-raw-measurement-reporting-views.sql"
  "migration-107-penalty-scaling.sql"
  "migration-108-team-and-owner-lists.sql"
  "migration-109-window-modes-and-staffing-split.sql"
)

# Each migration's landing check: a query returning 1 when it is present.
# Keyed by the same order as MIGRATIONS.
CHECK_LABELS=(
  "103 · AssessmentPeriodStandards.resolver_key"
  "104 · ContractorPerformanceStandards.source_system + CK_CPS_Source"
  "105 · dbo.ReferenceValues"
  "106 · five reporting views"
  "107 · standard targets, ranged band amounts, assessed occurrence amounts"
  "108 · responsible_team and assigned_to reference values"
  "109 · cap_window_mode + the four Operator Staffing standards"
)
CHECK_QUERIES=(
  "SELECT COUNT(*) FROM sys.columns WHERE object_id=OBJECT_ID('dbo.AssessmentPeriodStandards') AND name='resolver_key'"
  "SELECT CASE WHEN COL_LENGTH('dbo.ContractorPerformanceStandards','source_system') IS NOT NULL AND EXISTS(SELECT 1 FROM sys.check_constraints WHERE name='CK_CPS_Source') THEN 1 ELSE 0 END"
  "SELECT CASE WHEN OBJECT_ID('dbo.ReferenceValues','U') IS NOT NULL THEN 1 ELSE 0 END"
  "SELECT COUNT(*) FROM sys.views WHERE name IN ('vw_OtpMonthlyRouteStop','vw_OtpDailyRouteStopHour','vw_MissedTrip','vw_GarageDeparture','vw_MeasurementFeedHealth')"
  "SELECT CASE WHEN COL_LENGTH('dbo.ContractorPerformanceStandards','target_value') IS NOT NULL AND COL_LENGTH('dbo.ContractorStandardTiers','penalty_amount_min') IS NOT NULL AND COL_LENGTH('dbo.ComplianceOccurrences','assessed_amount') IS NOT NULL AND COL_LENGTH('dbo.PeriodKpiAssessments','awaiting_amount_count') IS NOT NULL THEN 1 ELSE 0 END"
  "SELECT CASE WHEN EXISTS(SELECT 1 FROM dbo.ReferenceValues WHERE domain='responsible_team') AND EXISTS(SELECT 1 FROM dbo.ReferenceValues WHERE domain='assigned_to') THEN 1 ELSE 0 END"
  "SELECT CASE WHEN COL_LENGTH('dbo.ContractorPerformanceStandards','cap_window_mode') IS NOT NULL AND EXISTS(SELECT 1 FROM sys.check_constraints WHERE name='CK_CPS_CapWindowMode') AND (SELECT COUNT(*) FROM dbo.ContractorPerformanceStandards WHERE code IN ('OPERATOR_STAFFING_LEVEL','PIVOT_COVERAGE','PIVOT_MISUSE','UNQUALIFIED_OPERATOR')) = 4 THEN 1 ELSE 0 END"
)
CHECK_EXPECTED=("1" "1" "1" "5" "1" "1" "1")

# Set when this wizard opens the firewall itself, so stage 6 knows what to undo.
ADDED_FIREWALL_RULE=""

# run_sql "<query>" — one scalar query, value only. Password comes from the
# environment, never the command line, so it stays out of `ps` output.
run_sql() {
  SQLCMDPASSWORD="$SQL_PASSWORD" sqlcmd -S "$SQL_FQDN" -d "$SQL_DATABASE" -U "$SQL_ADMIN" \
    -N -l 60 -b -h-1 -W -Q "SET NOCOUNT ON; $1" 2>&1
}

banner "Apply pending migrations to dev"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Preflight"
say "Applying to $SQL_DATABASE on $SQL_SERVER:"
for m in "${MIGRATIONS[@]}"; do step "$m"; done
printf '\n'
note "All four declare themselves re-runnable, so applying one that already"
note "ran is a no-op rather than a second write. That is what makes this"
note "safe to run without first proving which are outstanding."
printf '\n'

missing=0
for m in "${MIGRATIONS[@]}"; do
  [[ -f "$SQL_DIR/$m" ]] || { warn "missing: $SQL_DIR/$m"; missing=1; }
done
(( missing )) && { warn "Fetch main first: git fetch origin main && git merge origin/main"; exit 1; }
say "✓ all four migration files present"

command -v sqlcmd >/dev/null 2>&1 || { warn "sqlcmd not found. brew install sqlcmd"; exit 1; }
say "✓ sqlcmd $(sqlcmd --version 2>/dev/null | awk '/Version/{print $2}')"

command -v az >/dev/null 2>&1 || { warn "Azure CLI not found — needed for the network check."; exit 1; }
az account show >/dev/null 2>&1 || { warn "Not logged in. Run: az login"; exit 1; }
say "✓ Azure CLI signed in to $(az account show --query name -o tsv)"
printf '\n'
pause "Ready?"

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Network path"
say "The dev SQL server is private by design. Two things have to be true for"
say "a laptop to reach it: public access enabled, and a firewall rule for"
say "this machine's public IP."
printf '\n'

PUBLIC_ACCESS=$(az sql server show -g "$RESOURCE_GROUP" -n "$SQL_SERVER" --query publicNetworkAccess -o tsv)
MY_IP=$(curl -fsS https://api.ipify.org || true)
[[ -n "$MY_IP" ]] || { warn "Could not determine this machine's public IP."; exit 1; }
say "This machine: $MY_IP"
say "Public network access: $PUBLIC_ACCESS"

if [[ "$PUBLIC_ACCESS" != "Enabled" ]]; then
  warn "Public access is Disabled — nothing can connect from here."
  if confirm "Enable it for the duration of this run?"; then
    az sql server update -g "$RESOURCE_GROUP" -n "$SQL_SERVER" --enable-public-network true >/dev/null
    ADDED_PUBLIC_ACCESS=1
    say "✓ enabled — stage 6 turns it back off"
  else
    warn "Cannot continue without it."; exit 1
  fi
fi

if az sql server firewall-rule list -g "$RESOURCE_GROUP" -s "$SQL_SERVER" \
     --query "[?startIpAddress=='$MY_IP'] | length(@)" -o tsv | grep -qv '^0$'; then
  say "✓ a firewall rule already covers $MY_IP"
else
  say "No firewall rule covers this IP yet."
  ADDED_FIREWALL_RULE="wizard-$(date +%Y%m%d-%H%M%S)"
  if confirm "Add a rule for $MY_IP named $ADDED_FIREWALL_RULE?"; then
    az sql server firewall-rule create -g "$RESOURCE_GROUP" -s "$SQL_SERVER" \
      -n "$ADDED_FIREWALL_RULE" --start-ip-address "$MY_IP" --end-ip-address "$MY_IP" >/dev/null
    say "✓ added — stage 6 removes it"
  else
    ADDED_FIREWALL_RULE=""; warn "Cannot continue without it."; exit 1
  fi
fi
printf '\n'
pause "Continue?"

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Connect"
say "The admin password lives in Key Vault kv-mvta-dev-mvta-jx4471, which is"
say "itself private-only — so it cannot be fetched from this machine and you"
say "need to paste it. It is read into this shell only and never written to"
say "disk, a log, or the process list."
printf '\n'
say "Server:   $SQL_FQDN"
say "Database: $SQL_DATABASE"
say "Login:    $SQL_ADMIN"
printf '\n'

ask_secret SQL_PASSWORD "Password for $SQL_ADMIN:"
[[ -n "$SQL_PASSWORD" ]] || { warn "No password entered."; exit 1; }

say "Testing the connection (the database is serverless and may need a"
note "moment to resume if it has auto-paused)…"
if ! probe=$(run_sql "SELECT 1"); then
  warn "Could not connect:"
  printf '  %s\n' "$probe"
  exit 1
fi
say "✓ connected"
printf '\n'
pause "Apply the migrations?"

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Apply"
say "Running each file in numeric order. sqlcmd stops on the first error,"
say "and so does this loop — a later migration can depend on an earlier one."
printf '\n'

for m in "${MIGRATIONS[@]}"; do
  printf '  %s▸%s %s\n' "$BLUE" "$RESET" "$m"
  if SQLCMDPASSWORD="$SQL_PASSWORD" sqlcmd -S "$SQL_FQDN" -d "$SQL_DATABASE" -U "$SQL_ADMIN" \
       -N -l 60 -b -i "$SQL_DIR/$m" 2>&1 | sed 's/^/      /'; then
    printf '  %s✓%s %s\n\n' "$GREEN" "$RESET" "$m"
  else
    printf '\n'
    warn "$m failed — stopping here."
    note "Nothing after it has run. Fix the cause and re-run this wizard;"
    note "the migrations already applied will no-op on the second pass."
    exit 1
  fi
done
say "All four applied."
printf '\n'
pause "Verify?"

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Verify"
say "Reading the schema back, rather than trusting the exit codes above."
printf '\n'

failures=0
for i in "${!CHECK_LABELS[@]}"; do
  actual=$(run_sql "${CHECK_QUERIES[$i]}" | tr -d '[:space:]')
  if [[ "$actual" == "${CHECK_EXPECTED[$i]}" ]]; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "${CHECK_LABELS[$i]}"
  else
    printf '  %s✗%s %s %s(expected %s, got %s)%s\n' \
      "$RED" "$RESET" "${CHECK_LABELS[$i]}" "$DIM" "${CHECK_EXPECTED[$i]}" "${actual:-nothing}" "$RESET"
    failures=$((failures + 1))
  fi
done
printf '\n'

if (( failures )); then
  warn "$failures check(s) failed — the schema is not where it should be."
  SKIPPED+=("$failures migration check(s) failed — see the verify stage above")
else
  say "Schema matches. One last look at the new views:"
  printf '\n'
  run_sql "SELECT CONCAT(name, '  ', FORMAT(create_date,'yyyy-MM-dd HH:mm'))
           FROM sys.views WHERE name LIKE 'vw_Otp%' OR name IN
           ('vw_MissedTrip','vw_GarageDeparture','vw_MeasurementFeedHealth')" | sed 's/^/      /'
fi
printf '\n'
pause "Continue to close-down?"

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Close the door"
say "HANDOFF §5 rule 7: don't leave the dev server reachable from the"
say "internet. This stage undoes only what this wizard opened."
printf '\n'

if [[ -n "$ADDED_FIREWALL_RULE" ]]; then
  if confirm "Remove the firewall rule $ADDED_FIREWALL_RULE?"; then
    az sql server firewall-rule delete -g "$RESOURCE_GROUP" -s "$SQL_SERVER" -n "$ADDED_FIREWALL_RULE" >/dev/null
    say "✓ removed"
  else
    SKIPPED+=("firewall rule $ADDED_FIREWALL_RULE still open on $SQL_SERVER")
  fi
else
  note "No firewall rule was added by this run — leaving existing rules alone."
fi

if [[ -n "${ADDED_PUBLIC_ACCESS:-}" ]]; then
  if confirm "Set public network access back to Disabled?"; then
    az sql server update -g "$RESOURCE_GROUP" -n "$SQL_SERVER" --enable-public-network false >/dev/null
    say "✓ disabled"
  else
    SKIPPED+=("public network access left Enabled on $SQL_SERVER")
  fi
else
  warn "Public access was already Enabled before this run, so it is left as"
  note "found. It has been open since at least 2026-09-03 — worth closing"
  note "separately if nothing else needs it:"
  note "  az sql server update -g $RESOURCE_GROUP -n $SQL_SERVER --enable-public-network false"
fi

printf '\n'
say "Still outstanding for Power BI, unaffected by this run:"
step "the mvta_reporting_ro login is not provisioned, so every GRANT in"
note "  migrations 031 and 106 is still a no-op"
step "no gateway VM exists — design §10 has the shape"

finish
