#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Identifiers this wizard remembers between runs. Never the client secret -
# that goes from Entra into Key Vault without touching disk in the clear or
# appearing in any command line.
ENV_FILE="${ENV_FILE:-$HOME/.mvta-onboard-dm-health.env}"

GRAPH="https://graph.microsoft.com/v1.0"
SITES_SELECTED_ROLE="883ea226-0bf2-4a8f-9f9d-92c9162a727d"
GRAPH_APP_ID="00000003-0000-0000-c000-000000000000"

banner "Decision Matrix — SharePoint document identity"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight — who you are, and what you can reach"
say "Steps 1-5 of the runbook are tenant actions. They need a tenant"
say "administrator with Sites.FullControl.All, which is NOT a permission the"
say "application being created ever holds."
printf '\n'

if ! az account show >/dev/null 2>&1; then
  warn "not signed in. Run: az login"
  exit 1
fi
note "signed in as $(az account show --query user.name -o tsv) (tenant $(az account show --query tenantId -o tsv))"

ask ONBOARD_ENV "Which environment is this identity for? (dev/prod)"
write_env ONBOARD_ENV "$ONBOARD_ENV"

ask SITE_ID "Graph site id of the approved library's site:"
write_env SITE_ID "$SITE_ID"

ask VAULT_NAME "Key Vault name for that environment:"
write_env VAULT_NAME "$VAULT_NAME"

printf '\n'
say "Checking you can read the site's existing grants. This is the same"
say "permission step 4 needs, so a failure here is better found now."
if az rest --method get --url "$GRAPH/sites/$SITE_ID/permissions" >/dev/null 2>&1; then
  printf '  %s✓%s site grants are readable — you have Sites.FullControl.All\n' "$GREEN" "$RESET"
else
  warn "cannot read $GRAPH/sites/$SITE_ID/permissions"
  note "Either the site id is wrong, or this account lacks Sites.FullControl.All."
  note "Stage 5 will fail the same way. Fix this before continuing."
  confirm "Continue anyway?" || exit 1
fi

printf '\n'
say "Checking the vault is reachable. OnBoard's vaults deny public network"
say "access, so this must run from an approved network."
if az keyvault secret list --vault-name "$VAULT_NAME" --maxresults 1 >/dev/null 2>&1; then
  printf '  %s✓%s %s is reachable\n' "$GREEN" "$RESET" "$VAULT_NAME"
else
  warn "cannot list secrets in $VAULT_NAME"
  note "Stage 6 stores the client secret there and will fail. Connect to an"
  note "approved network (or add your IP to the vault firewall) first."
  confirm "Continue anyway?" || exit 1
fi
pause "Preflight done. Enter to continue."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Register the application"
say "One registration per environment. It is never signed into by a person:"
say "no redirect URI, no platform configuration, no exposed API."
printf '\n'

APP_NAME="MVTA OnBoard — Decision Matrix Documents ($ONBOARD_ENV)"
note "name: $APP_NAME"

EXISTING_APP_ID=$(az ad app list --display-name "$APP_NAME" --query "[0].appId" -o tsv 2>/dev/null || true)
if [[ -n "$EXISTING_APP_ID" ]]; then
  note "a registration with this name already exists: $EXISTING_APP_ID"
  say "Re-using it rather than creating a second identity with the same name."
  APP_ID="$EXISTING_APP_ID"
else
  confirm "Create this registration now?" || { warn "stopped without creating anything"; exit 1; }
  APP_ID=$(az ad app create --display-name "$APP_NAME" --sign-in-audience AzureADMyOrg --query appId -o tsv)
  printf '  %s✓ created%s application %s\n' "$GREEN" "$RESET" "$APP_ID"
fi
write_env APP_ID "$APP_ID"

# The service principal is what a site grant and a role assignment attach to.
if ! az ad sp show --id "$APP_ID" >/dev/null 2>&1; then
  az ad sp create --id "$APP_ID" >/dev/null
  printf '  %s✓ created%s service principal\n' "$GREEN" "$RESET"
else
  note "service principal already exists"
fi
pause "Enter to continue."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Add Sites.Selected — and nothing else"
say "Sites.Selected grants nothing on its own. It only makes stage 5 possible,"
say "which is exactly why it is the right permission here."
printf '\n'
warn "Do not add Sites.Read.All, Files.Read.All or Sites.FullControl.All."
note "Step 4 does not require them OF THIS APPLICATION - they belong to the"
note "administrator making the grant."
printf '\n'
az ad app permission add --id "$APP_ID" \
  --api "$GRAPH_APP_ID" \
  --api-permissions "${SITES_SELECTED_ROLE}=Role" >/dev/null 2>&1 || true
printf '  %s✓%s requested Microsoft Graph → Application → Sites.Selected\n' "$GREEN" "$RESET"
note "requested, not yet consented - that is the next stage"
pause "Enter to continue."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Grant admin consent"
say "A tenant administrator consents for the organization. Until this lands,"
say "the application holds a request, not a permission."
printf '\n'
if az ad app permission admin-consent --id "$APP_ID" >/dev/null 2>&1; then
  printf '  %s✓%s consent granted\n' "$GREEN" "$RESET"
else
  warn "could not grant consent from the CLI (this often needs the portal)"
  open_url "https://entra.microsoft.com/#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/CallAnAPI/appId/$APP_ID"
  step "API permissions → Grant admin consent for <tenant> → Yes."
  pause "Press Enter once consent shows as Granted."
fi

SP_OBJECT_ID=$(az ad sp show --id "$APP_ID" --query id -o tsv)
if az rest --method get \
    --url "$GRAPH/servicePrincipals/$SP_OBJECT_ID/appRoleAssignments" \
    --query "value[?appRoleId=='$SITES_SELECTED_ROLE'] | [0].appRoleId" -o tsv 2>/dev/null | grep -q .; then
  printf '  %s✓ verified%s Sites.Selected is consented\n' "$GREEN" "$RESET"
else
  warn "Sites.Selected does not show as consented yet"
  note "Directory changes can lag a few seconds; re-run this wizard to re-check."
  confirm "Continue anyway?" || exit 1
fi
pause "Enter to continue."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Grant the application read on the approved site"
say "This is the grant that actually opens the library, and the one whose"
say "absence reads in the console as \"OnBoard has not been granted access\"."
printf '\n'
note "role: read - OnBoard reads approved documents, it never writes to SharePoint"
printf '\n'

if az rest --method get --url "$GRAPH/sites/$SITE_ID/permissions" \
     --query "value[?contains(to_string(grantedToIdentities), '$APP_ID')] | [0].id" -o tsv 2>/dev/null | grep -q .; then
  note "this application already has a grant on this site"
  PERMISSION_ID=$(az rest --method get --url "$GRAPH/sites/$SITE_ID/permissions" \
    --query "value[?contains(to_string(grantedToIdentities), '$APP_ID')] | [0].id" -o tsv)
else
  confirm "Grant read on this site now?" || { warn "stopped before granting"; exit 1; }
  BODY=$(printf '{"roles":["read"],"grantedToIdentities":[{"application":{"id":"%s","displayName":"%s"}}]}' "$APP_ID" "$APP_NAME")
  PERMISSION_ID=$(az rest --method post --url "$GRAPH/sites/$SITE_ID/permissions" \
    --headers "Content-Type=application/json" --body "$BODY" --query id -o tsv)
  printf '  %s✓ granted%s\n' "$GREEN" "$RESET"
fi
write_env PERMISSION_ID "$PERMISSION_ID"
note "Revoking later is a DELETE on this permission id - no redeploy needed:"
note "  az rest --method delete --url $GRAPH/sites/<site>/permissions/$PERMISSION_ID"
pause "Enter to continue."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Create the client secret, and put it straight into Key Vault"
say "The secret goes from Entra into the vault without being displayed, written"
say "to $ENV_FILE, or passed on a command line where ps could see it."
printf '\n'
warn "Note the expiry and set a calendar reminder before it."
note "An expired secret makes every document read fail, and today's failure"
note "message calls that a document problem rather than an expired credential."
printf '\n'
confirm "Create a 1-year secret and store it as decision-matrix-health-client-secret?" \
  || { warn "stopped before creating a secret"; exit 1; }

umask 077
SECRET_FILE=$(mktemp)
trap 'rm -f "$SECRET_FILE"' EXIT

az ad app credential reset --id "$APP_ID" --append \
  --display-name "onboard-$ONBOARD_ENV" --years 1 \
  --query password -o tsv | tr -d '\n' > "$SECRET_FILE"

EXPIRES=$(az ad app credential list --id "$APP_ID" --query "[-1].endDateTime" -o tsv 2>/dev/null || echo "unknown")
printf '  %s✓ created%s secret on the registration (expires %s)\n' "$GREEN" "$RESET" "$EXPIRES"

az keyvault secret set --vault-name "$VAULT_NAME" \
  --name "decision-matrix-health-client-secret" \
  --file "$SECRET_FILE" --output none
printf '  %s✓ stored%s in %s as decision-matrix-health-client-secret\n' "$GREEN" "$RESET" "$VAULT_NAME"

printf '\n'
say "Proving consent and the site grant together, as the application itself:"
TENANT_ID=$(az account show --query tenantId -o tsv)
TOKEN=$(curl -s -X POST "https://login.microsoftonline.com/$TENANT_ID/oauth2/v2.0/token" \
  -d "client_id=$APP_ID" -d "grant_type=client_credentials" \
  -d "scope=https://graph.microsoft.com/.default" \
  --data-urlencode "client_secret@$SECRET_FILE" \
  | python3 -c 'import sys,json; print(json.load(sys.stdin).get("access_token",""))' 2>/dev/null || true)

if [[ -z "$TOKEN" ]]; then
  warn "could not get an app-only token - consent may not have propagated yet"
else
  CODE=$(curl -s -o /dev/null -w '%{http_code}' \
    -H "Authorization: Bearer $TOKEN" "$GRAPH/sites/$SITE_ID/drive/root/children")
  case "$CODE" in
    200) printf '  %s✓ 200%s - the application can read the library\n' "$GREEN" "$RESET" ;;
    403) warn "403 - consent or the site grant did not take effect (stages 4 and 5)" ;;
    *)   warn "HTTP $CODE from Graph - see the runbook's verification list" ;;
  esac
fi

rm -f "$SECRET_FILE"; trap - EXIT
pause "Enter to continue."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Hand the client id to the repository"
say "Steps 1-5 are done. Step 6 is a one-line change in this repository, and"
say "step 7 is a deploy."
printf '\n'
printf '  %s%s%s\n' "$BOLD" "$APP_ID" "$RESET"
printf '\n'
step "Put that id in infra-phase1/parameters/phase1-$ONBOARD_ENV.parameters.json:"
note "    \"decisionMatrixHealthClientId\": { \"value\": \"$APP_ID\" },"
step "Open a PR, merge it, and deploy infra-phase1."
step "Confirm the Function App restarted with DECISION_MATRIX_HEALTH_CLIENT_ID"
note "    and DECISION_MATRIX_HEALTH_CLIENT_SECRET present."
printf '\n'
note "The secret itself never enters the repository: Bicep emits a Key Vault"
note "reference to decision-matrix-health-client-secret, and the app's"
note "managed identity reads it at runtime."
printf '\n'
warn "Rotating the secret later is a vault operation - no redeploy."

finish
